### ISSUE TITLE
As Security Server administrator I want  time-stamped records need to be archived and archived records removed from database

### ISSUE THREAD

**Issue by VassilMarjunits** [vrk-kpa/xroad-joint-development#103]
**Affected components**: Security Server
**Affected documentation**: -
**Estimated delivery**: -
**External reference**:  https://jira.ria.ee/browse/XTE-305

**Problem**
In case of large SOAP messages, time stamped records are sometimes not removed from the database due to memeory problems.
While looking into the issues we've discovered some aspects of archiving that could be done better.

*The current archiving logic does not reasonably support large SOAP messages. Current constants that try to regulate memory usage don't really solve the problem.
*The call for the archiving script is currently not in a reasonable place (inside a DB session and depends on the aforementioned constants)
*Compliance to the max size of archived files can be done more accurately
*Saving temporary ASiC files to disk can be avoided
*ASiC filename lenghts should be checked and shortened if necessary, because the system supports 255 characters max but the file name currently uses the message id of the SOAP message which has varying lenght.
*The archiving cycle should be divided to multiple DB sessions and not be performed in a single session.

**Acceptance criteria**
the archiving logic to support large SOAP messages

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
