### ISSUE TITLE
Bug: Race condition when adding a security server client

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#105]
**Affected components**: - Security Server
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-301

**Problem**

Currently there exists a race condition, where it is possible to add more than one security server client with the same name (via the web interface with "unfortunate" double clicks or with direct queries). These clients cannot be deleted afterwards.

**Acceptance criteria**
- Race condition fixed
- Optional: fix issues with "unfortunate" double clicks in the web interface

**Comment by VitaliStupin** [comment]
Fixed in 6.9.4 version
