### ISSUE TITLE
Bug: Deleting a security server client's WSDL causes the deletion of ACL-s under other WSDL-s of the same client

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#106]
**Affected components**: - Security Server
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-319

**Problem**
Steps to reproduce:

1. Add multiple WSDL-s under one subsystem
2. Add access rights to services under WSDL-s
3. Delete one WSDL
4. ACL of remaining WSDL is deleted

**Acceptance criteria**
- Deleting a client's WSDL does not cause the deletion of ACL-s of remaining WSDL's services

**Comment by VitaliStupin** [comment]
Fixed in 6.9.4 version
