### ISSUE TITLE
NFR point 3.2.3 is unclear

### ISSUE THREAD

**Issue by margusf** [vrk-kpa/xroad-joint-development#11]
In requirement 3.2.3 it is unclear which /lib directory is meant. Does it mean /lib directory of the computer where the component is installed? Or /lib directory in installation package/jar file?

In the first case, /lib is not the best place to install application libraries. Current system follows Debian guidelines and installs libraries under /usr/share/xroad.

If the second case, this should be explicitly stated taking also into account that each component is installed from several packages and JARs.

**Comment by VitaliStupin** [comment]
The original intention was to say that libraries required for each component must be packaged with that component. In other words you should not rely on application servers to have all the required libraries and in the same way unless you specify a deb (or rpm) dependency you must package all the libraries with the component. I agree that the location "/lib" is misleading in that requirement. I could propose the following change:

3.2.3 All libraries needed for the operation of the component MUST be either packaged with the same component or component's installation package MUST depend on appropriate library packages.

Also as soon as we specify that we use deb and rpm systems for packaging, it should be obvious that it is required to use Debian and Redhat guidelines for the locations of libraries.

**Comment by VitaliStupin** [comment]
NFR updated
