### ISSUE TITLE
Bug: Typo in xtee6/packages/default-configuration/proxy.ini

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#111]
**Affected components**: - Security Server
**Affected documentation**: 
**Estimated delivery**: - 6.9.3
**External reference**: - https://jira.ria.ee/browse/XTE-322

**Problem**

Typo in configuration file.

; Client Proxy to Server Proxy connection timeout in milliseconds
client-timout=300000

**Acceptance criteria**
- "client-timout" changed to "client-timeout" in source code

**Comment by VitaliStupin** [comment]
Fixed in 6.9.4 version
