### ISSUE TITLE
As a Central Server and X-road Centre Manager I need functionality to deactivate subsystem (Member) temporary or for defined period 

### ISSUE THREAD

**Issue by VassilMarjunits** [vrk-kpa/xroad-joint-development#124]
**Affected components**: Central Server
**Affected documentation**: UG-CS, US-SS?
**Estimated delivery**: -
**External reference**: -

**Problem**
In some cases it is necessary to temporarily disable Subsystem or entire Member access to X-Road:
* Subsystem (Member) does not comply with X-road requirements anymore or have been violating requirements.
* Subsystem have been approved by mistake.

In that case deleting and recreating Subsystem/Member leads to unnecessary management effort.

**Acceptance criteria**
* Functionality to disable Subsystem (Member) temporary or for defined period is created.

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
