### ISSUE TITLE
As an X-Road Instance Maintainer I want support for "NEE" member class in our certificate extractor method

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#127]
**Affected components**: - N/A
**Affected documentation**: - N/A
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-330

**Problem**
Currently the extractor method we use at RIA for certificates provided by SK ID Solutions AS does not support foreign (i.e. not Estonian) organizations. We would need to add support for a new member class (we call it "NEE" for "not Estonian") in the extractor method, based on the certificate profile provided by SK ID Solutions AS.

The method we currently use can be found here: https://github.com/ria-ee/X-Road/blob/61416dfe310740ba908836ba8526499e631b6dfa/src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl/SkKlass3CertificateProfileInfoProvider.java.

**Acceptance criteria**
- "NEE" member class supported in extractor method for certificates provided by SK ID Solutions AS.

**Comment by VitaliStupin** [comment]
Fixed in 6.16.0
