### ISSUE TITLE
BUG: Nginx cant access global configuration after restore of Central Server

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#130]
**Affected components**: Center
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-729

**Problem**
If Backup/Restore is made in central server then global configuration becomes unavailable. The problem is that nginx (www-data user) cant access /var/lib/xroad directory anymore.

Before restore:
ls -lad /var/lib/xroad
drwxrwxr-x 5 xroad xroad 4096 Feb 20 15:58 /var/lib/xroad

After restore:
ls -lad /var/lib/xroad
drwxrwx--- 5 xroad xroad 4096 Mar 13 12:05 /var/lib/xroad

Hotfix:
chmod o+rx /var/lib/xroad

**Acceptance criteria**
- Restore bug is fixed.

**Comment by hanhaka** [comment]
Fixed in version 6.13.0
