### ISSUE TITLE
As a Security Server Administrator I want a client-side timeout for OCSP queries on port 5577

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#132]
**Affected components**: - ClientProxy
**Affected documentation**: - ug-syspar_x-road_v6_system_parameters
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-308

**Problem**
If the ServerProxy has issues providing an OCSP response to the client on port 5577, the ClientProxy's connection will just hang since currently there doesn't appear to be a time-out. A solution would be adding a configurable time-out.

**Acceptance criteria**
- Configurable time-out added for ClientProxy's OCSP queries on port 5577

**Comment by VitaliStupin** [comment]
Released in version 6.12.0
