### ISSUE TITLE
adding new wsdl

### ISSUE THREAD

**Issue by alweiler** [vrk-kpa/xroad-joint-development#138]
**Affected components**: 6.8.6.20161020095957
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
If we are adding new wsdl, then I must manually change all addresses from localhost to ip address

For example 

http://localhost:8080/axis2/services/DigiluguRegistriteTeenused
![screenshot from 2017-03-24 13-52-40](https://cloud.githubusercontent.com/assets/714591/24293603/4467665e-109b-11e7-9b2c-9dec198dd6a8.png)

**Acceptance criteria**
- ...

**Comment by JyrgenSuvalov** [comment]
You should be able to use the "Apply to all in WSDL" check when editing a service URL. Have you encountered an error with it?

**Comment by alweiler** [comment]
Ok, so it works. But better way will be if adding wsdl, then it writes this ip address on all lines

**Comment by JyrgenSuvalov** [comment]
Service URLs are taken from the WSDL.

<soap:address location="http://INSERT_CORRECT_SERVICE_URL"/>
