### ISSUE TITLE
Vendors should use forks?

### ISSUE THREAD

**Issue by iluwatar** [vrk-kpa/xroad-joint-development#14]
Currently the workflow suggests that all the vendors could work in the same repository in different branches. For this to work, the vendors would need to use VPN connections to access the XM repository. Additionally the access rights for the XM would need to be set per branch since it is not desirable that everyone has push access to `master` or `develop` for example.

I would propose that the main workflow for vendors would use forks. To contribute to XM the vendor would need to fork the repository, work the changes in the forked repository and then using a pull request ask that the work is integrated into XM/develop. 

This way we can eliminate both the problems listed above. The vendor has full access to all the branches in his fork and there is no need to use VPN for access.

**Comment by PriitParmakson** [comment]
Technically, fork is a GitHub term? Should we use 'cloned (or forked) repository'?

**Comment by iluwatar** [comment]
Technically clone vs fork is quite the same - make a copy of the repository. But the intended workflow is a bit different.

When a repository is cloned the intention is to make changes and integrate them to the upstream repository i.e. work directly on the XM.

When a repository is forked it means you create a copy of the repository on your own account. There's an example here, it's the relationship between https://github.com/vrk-kpa/xroad-joint-development and https://github.com/e-gov/xroad-joint-development. When you want to modify it you clone https://github.com/e-gov/xroad-joint-development on your own computer, make the changes and push them to https://github.com/e-gov/xroad-joint-development. The next step is to create a pull request from https://github.com/e-gov/xroad-joint-development to https://github.com/vrk-kpa/xroad-joint-development.

**Comment by PriitParmakson** [comment]
Ok, Ilkka, do these differences bear for BitBucket (Stash) too?

**Comment by iluwatar** [comment]
Yes, the terminology is the same for Stash and Bitbucket.

**Comment by PriitParmakson** [comment]
Ok, thank you, Ilkka, for explaining things.
