### ISSUE TITLE
As X-Road user I want that publiced services WSDL-s comply to X-Road Message Protocol

### ISSUE THREAD

**Issue by tao-aldo** [vrk-kpa/xroad-joint-development#149]
**Affected components**: wsdl-validator
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
Often service description wsdls don't compile to X-Road Message Protocol and some even not valid as wsdl.
Seems, that included wsdl-validator is too lax and not working correctly.

Examples:
- xRoadInstance=EE&memberClass=GOV&memberCode=70003218&subsystemCode=jvis&serviceCode=paigaldis_liigid&version=v1 - not valid as wsdl and not valid as x-road message (3.2 Describing Services with WSDL)
- xRoadInstance=ee-dev&memberClass=GOV&memberCode=70000310&subsystemCode=muinas&serviceCode=EHRObjektid&version=v1 - not valid as wsdl
- xRoadInstance=EE&memberClass=GOV&memberCode=70000349&subsystemCode=makis&serviceCode=makisTaxRates&version=v1 - not valid as x-road message

Also seen errors like <element name="Elukoht " (space in element name) and validator tolerates soap-encoding array type as element type. After complaining service owner already fixed them.

**Acceptance criteria**

- wsdl-validator cannot be disabled in server configutration
- wsdl-validator fully validates service descriptions
- wsdl-validator rejects ill-formed descriptions
- strict wsdl validators (like XMLSpy) and client generators accepts service descriptions
- all services descriptions fully comply X-Road Message Protocol

**Comment by VitaliStupin** [comment]
It looks like Apache CXF used for validation of WSDL documents ignores a lot of problems with WSDLs. We should consider switching to a better wsdl validator.

**Comment by VitaliStupin** [comment]
Additionaly we should store WSDL's in security server to avoid the problem when WSDL is changed after passing validation.

**Comment by petkivim** [comment]
There's an issues regarding updating the WSDL validator in the X-Road backlog:

https://jira.niis.org/browse/XRDDEV-8

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
