### ISSUE TITLE
As Security Server administrator i need properly working OCSP validity check

### ISSUE THREAD

**Issue by VassilMarjunits** [vrk-kpa/xroad-joint-development#157]
**Affected components**: Security Server
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.ria.ee/browse/XTE-343

**Problem**
Sometime during TLS handshake  valid AUTH certificate can be handled as non valid.
It can happens when Client SServer uses Service SServer OCSP from own OCSP cache, but when handshake is started, on this moment, Service SServer side OCSP can be already expired (i.e. valid for last second). 

Its cause error log and message transaction is failed.
Fault message "Service provider did not send correct authentication certificate"

**Acceptance criteria**
Better control of OCSP validity check.

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
