### ISSUE TITLE
As a Security Server Administrator I want that all querys and responses are logged in messagelog.logrecord table

### ISSUE THREAD

**Issue by tuudik** [vrk-kpa/xroad-joint-development#158]
**Affected components**: messagelog
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
When posting query that is failing, for example access is denied, it is not logged in messagelog. Only the query is available from messagelog.logrecord table

**Acceptance criteria**
- All responses and querys are logged.

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
