### ISSUE TITLE
As a Security Server Administrator I want more meta data to be available in messagelog.logrecords table

### ISSUE THREAD

**Issue by tuudik** [vrk-kpa/xroad-joint-development#159]
**Affected components**: messagelog
**Affected documentation**: https://github.com/ria-ee/X-Road/blob/develop/doc/DataModels/dm-ml_x-road_message_log_data_model.md
**Estimated delivery**: -
**External reference**: -

**Problem**
We are planning to mirror the logs to ELK stack. Unfortunately noticed that there is missing some metadata fromthe logrecords table.

Proposal to add following columns/data to the table:
- request.time.utc (human readable in GMT/UTC, not epoch only)
- response.time.utc (human readable in GMT/UTC)
- client.xRoadInstance
- service.xRoadInstance
- service.memberClass
- service.memberCode
- service.subsystemCode
- service.serviceCode
- service.serviceVersion

And rename following columns:
- memberClass -> client.memberClass
- memberCode -> client.memberCode
- subsystemCode -> client.subsystemCode

This would make exporting the data to ELK stack much much easier and it wouldnt be neccessay to do additional grok "message" parsing in logstash.

**Acceptance criteria**
- Proposal accepted and implemented
- Documentation updated

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
