### ISSUE TITLE
As a Security Server Administrator I want the confclient to remove it's temporary files in error situations

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#164]
**Affected components**: - confclient
**Affected documentation**: - 
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-357

**Problem**
Temporary files that are a byproduct of the atomic save are not removed in error situations (e.g. disk full).
/etc/xroad/globalconf/ee-dev# ls -lart | grep 'expires*' | wc -l
1397

https://github.com/ria-ee/X-Road/blob/develop/src/common-util/src/main/java/ee/ria/xroad/common/util/AtomicSave.java

**Acceptance criteria**
- Temporary files are removed correctly

**Comment by VitaliStupin** [comment]
Fixed in 6.16.0
