### ISSUE TITLE
Bug: X-Road metadata service getWsdl is not documented

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#166]
**Affected components**: -
**Affected documentation**: PR-META
**Estimated delivery**: Q4 / 2017
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-1027

**Problem**
PR-META document specifies only "http://SECURITYSERVER/wsdl" service for retrieving WSDL's, but that is actually implementation specific service, and internally used X-Road getWsdl meta service is not documented at all.

**Acceptance criteria**
- Protocol document is updated.

**Comment by hanhaka** [comment]
Fixed in 6.17.0, see: https://github.com/ria-ee/X-Road/pull/75
