### ISSUE TITLE
As X-Road user I want that Security Server stores global configuration in in-memory cache so that message processing would be faster.

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#17]
**Affected components**: configuration client
**Affected documentation**: -
**Estimated delivery**: May 2016.
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-350

Acceptance criteria:
- during message processing global configuration is fetched from in-memory cache by proxy
- in-memory cache is updated each time when global configuration stored on disk is updated
- performance tests are run after the change has been implemented

**Comment by petkivim** [comment]
Done. Initial performance tests show that performance would have improved around 10 %. Needs further testing.

**Comment by PriitParmakson** [comment]
Great work!
