### ISSUE TITLE
As a Security Server Administrator, I want my Substem->Adapter connection to obey Adapter Server's CertificateRequest for client authentication

### ISSUE THREAD

**Issue by kimmormh** [vrk-kpa/xroad-joint-development#174]
**Affected components**:
ServerProxy
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
My AS/IS requires clients to present a valid client certificate in order to use the system and select the services available to any given client.

The authentication and verification is done outside of the adapter module and cannot (And should not) be disabled due to the nature of the service. This particular back end service advertises the accepted CAs.

When adding the wsdl (And naturally, when using the service), the Subsystem should obey server's CertificateRequest messages in the handshake

**Acceptance criteria**
- When presented with CertificateRequest message during TLS handshake, Subsystem should present its internal TLS certificate
- If CertificateRequest message advertises a list of accepted CAs, and the subsystem has multiple, it should choose one that is signed by one of the advertised CAs

**Comment by petkivim** [comment]
Fixed by #214 and #144.
