### ISSUE TITLE
As X-Road user I want that configuration items stored in the database are fetched only once per request so that message processing would be faster.

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#18]
**Affected components**: proxy
**Affected documentation**: ug-syspar_x-road_v6_system_parameters.odt_2.9_Y-881-1.docx
**Estimated delivery**: autumn 2016
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-351, https://github.com/vrk-kpa/xroad/pull/35

**Problem**
The per-server configuration (e.g. services and access rights) is stored into a local database. There are several database hits per request causing some performance overhead.

**Acceptance criteria**
- Security Server makes only one (or even none) database query per request
- Configuration items may ba cached and cache is refreshed frequently
- Database query is optimized

**Comment by hvainsalu** [comment]
Estimated delivery and components updated.

**Comment by hanhaka** [comment]
Implemented, reviewed, documentation updated and merged to GitHub:https://github.com/vrk-kpa/xroad/pull/35
