### ISSUE TITLE
As a Security Server Admin I want access rights fatal error to be more informative about the problem

### ISSUE THREAD

**Issue by qrlt** [vrk-kpa/xroad-joint-development#181]
**Affected components**: xroad-proxy

**Problem**
If the user logs in to the Security Server Administrator webview without having any x-road specific role(I.E. xroad-security-officer) then "Fatal system error - contact system administrator" occurs.
The error message does not explain to the user about the problem.
![xroad_6_16_0_not_initalized](https://user-images.githubusercontent.com/11455749/31176669-549d9e84-a91c-11e7-8a66-85ef98f460af.jpg)

**Acceptance criteria**
- Error message must inform the user about the access right problem.

**Comment by petkivim** [comment]
Related to the issue #52

**Comment by petkivim** [comment]
Transferred to X-Road Service Desk as an enhancement request.
