### ISSUE TITLE
As a Security Server Administrator I need UG-SS have information that Changing the parameter values in the configuration files requires restarting of the server.

### ISSUE THREAD

**Issue by VassilMarjunits** [vrk-kpa/xroad-joint-development#184]
**Affected components**: -
**Affected documentation**: UG-SS
**Estimated delivery**: -
**External reference**: -

**Problem**
UG-SS missing instruction of 
Changing the parameter values in the configuration files requires restarting of the server. 
i.e "Changing the Configuration of the Message Log"

**Acceptance criteria**
- UG-SS have information that Changing the parameter values in the configuration files requires restarting of the server. In addition link to UG-SYSPAR.

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road Backlog](https://jira.niis.org/projects/XRDDEV/).

[Sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account and get access to the [X-Road Backlog](https://jira.niis.org/projects/XRDDEV/).

This issue has been transferred to the X-Road Backlog:


https://jira.niis.org/browse/XRDDEV-43
