### ISSUE TITLE
As a Security Server Administrator I want OCSP log messages to be more verbal

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#187]
**Affected components**: - xroad-signer
**Affected documentation**: - None
**Estimated delivery**: - N/A
**External reference**: - https://jira.ria.ee/browse/XTE-386

**Problem**
OCSP Response status codes are a bit cryptic for debugging. For example:

e.r.x.s.certmanager.OcspClientWorker - Parsing OCSP response from http://ocsp.sk.ee/failed
org.bouncycastle.cert.ocsp.OCSPException: Invalid OCSP response status: 6

Response status code 6 stands for UNAUTHORIZED. Logging "Request not authorized" would be more informative for administrators.

**Acceptance criteria**
OCSP log messages are made more verbal.

**Comment by VitaliStupin** [comment]
Fixed in 6.17.0
