### ISSUE TITLE
As X-Road user I want that OCSP responses are verified once per request so that message processing time would be as short as possible.

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#19]
**Affected components**: server-proxy, client-proxy
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-352

**Problem**
Signing and authentication certificate's status is verified on each request (client security server seems to make 5 verifications per request, server 3).

Acceptance criteria:
- authentication certificate's OCSP response is verified once per request
- signcertificate's OCSP response is verified once per request
- verification results are cached and reused (must be defined in more detail)

**Comment by hvainsalu** [comment]
Add affected components.

**Comment by hanhaka** [comment]
Merged code changes to develop branch in VRK-KPA repository via commit:
https://github.com/vrk-kpa/xroad/pull/40

**Comment by hanhaka** [comment]
Commited to XM/develop (finnish-6.9.0 pull request). Will be available with 6.9 release.
