### ISSUE TITLE
As a Product Owner I want update the README.md file in X-Road Github repository so that the information is up to date

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#198]
**Affected components**: -
**Affected documentation**: README.md
**Estimated delivery**: Q4 / 2017
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-1057

**Problem**
Main page of X-Road Github repository needs two minor updates: 
- Update the list of 'Known organizations providing consultational X-Road services'
- Update the 'Support disclaimer' text as stated here:
"Current repository is collaboration platform between Finnish and Estonian governments for joint development of the X-Road. Cooperation is organized by the Nordic Institute for Interoperability Solutions (NIIS)."

**Acceptance criteria**
- README.md file is updated as described above

**Comment by hanhaka** [comment]
Agreed on 13.12.207 in Working Group meeting to start the work for this issue.

**Comment by margusf** [comment]
While we are at it, I would submit correction to the entry about Cybernetica:

- The official name of the company is "Cybernetica AS"
- The preferred homepage URL is https://cyber.ee

**Comment by hanhaka** [comment]
Thanks, I will update the Cybernetica related information as proposed by you.

**Comment by hanhaka** [comment]
Fixed in version 6.17.0. 
PR: https://github.com/ria-ee/X-Road/pull/73
