### ISSUE TITLE
Bug: Refreshing WSDLs after removing a service or replacing it with another service version causes the removal of the ACL of services with the same code

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#199]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-385

**Problem**

Service access rights are removed after refreshing a WSDL when:

- there are multiple versions of the service and one of them is removed before refreshing
- the version of a service is changed

**Acceptance criteria**
- Refreshing a WSDL does not remove any access rights

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
