### ISSUE TITLE
As a Security Server Administrator I want global configuration expiration check to use the correct global configuration elements

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#202]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-396

**Problem**
The global configuration expiration check and other operations that use the files in /etc/xroad/globalconf/ are not currently using /etc/xroad/globalconf/files to determine which elements to perform these operations on.

**Acceptance criteria**
- Global configuration operations are performed on files in accordance with /etc/xroad/globalconf/files

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
