### ISSUE TITLE
As a Security Server Administrator I want the configuration client to synchronize only valid global configuration elements 

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#203]
**Affected components**: - xroad-confclient
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-397

**Problem**

This is related to #202 - the configuration client needs to sync only configuration elements that are present in /etc/xroad/globalconf/files, i.e. add, remove and update only the files of valid elements of the globalconf after downloading it.

**Acceptance criteria**
- Only valid globalconf elements' files are synced

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
