### ISSUE TITLE
Bug: Internal TLS Certificate of Security Server cannot be changed using UI

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#205]
**Affected components**: UI
**Affected documentation**: -
**Estimated delivery**: Q1/2018
**External reference**: -

**Problem**
Internal TLS Certificate of Security Server cannot be changed using UI in version 6.16.0. If trying to create a new Generate Certificate Request in UI, it is causing error message (see picture ‘Generate Certificate Request.png’) and request is not possible to complete. The screen capture below illustrates the situation when the ‘Generate Certificate Request’-button was pressed on UI. Also the ‘Import’ -functionality (of Internal TLS Certificate) does not work as supposed i.e. certificates cannot be imported successfully.

![generate certificate request error](https://user-images.githubusercontent.com/6880618/34762163-736402b6-f5ef-11e7-9aea-b331816002cf.png)

**Acceptance criteria**
- Internal TLS Certificate of Security Server is possible to change using UI
- Generate Certificate Request and Import functionalities (and buttons in UI) are working correctly

**Comment by JyrgenSuvalov** [comment]
External reference - https://jira.ria.ee/browse/XTE-405

**Comment by hanhaka** [comment]
Fixed in 6.17.0
For more information, see https://github.com/ria-ee/X-Road/pull/78
