### ISSUE TITLE
As a Security Server Admin I want that Logback logging module is replaced by Slf4jRequestLog module so that logging functionality is improved

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#208]
**Affected components**: Logback
**Affected documentation**: -
**Estimated delivery**: Q2 / 2018
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-1058

**Problem**
Logback logging module is slightly outdated and it is not very robust module to use anymore. There are some bugs that are not fixed even they have been issued and open since 2015. For more information see https://github.com/eclipse/jetty.project/issues/509 and https://github.com/qos-ch/logback/pull/269

Due to above known bugs, some quick (and hopefully temporary) fixes was needed to implement to restore X-Road normal logging features. For more information see: https://github.com/vrk-kpa/X-Road/pull/86

Logging module should be replaced by some robust logging module for better functionality and to decrease the technical depth. Preferred solution is to use Slf4jRequestLog module (org.eclipse.jetty.server.Slf4jRequestLog). It offers better functionality with pretty much same features.

**Acceptance criteria**
- Logback logging module is replaced by Slf4jRequestLog module
- New implementation must provide the same functionality as the old Logback logging module provides
- Above mentioned temporary fixes are removed
- Documentation is updated

**Comment by petkivim** [comment]
Transferred to NIIS backlog:

https://jira.niis.org/browse/XRDDEV-10
