### ISSUE TITLE
As X-Road user I want that Security Server would add an additional message id to every request/response pair, so that even if id provided by service Client is not unique it would be possible to distinguish messages in message log.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#21]
Acceptance criteria:
- Table "logrecord" of database "messagelog" contains new column with new UUID's
- Requests and responses have the same unique UUID.
- Archived message log also contains new UUID
- If Security Server is asked for message logs with message id defined by service Client then resulting log must contain new UUID so that request/response pairs would be clearly distinguishable.

**Comment by margusf** [comment]
Is this a protocol-level feature or does it only concern message log?

**Comment by VitaliStupin** [comment]
Current concern is related to message log only. If some Client is sending queries with the same message id (xrd:id) then it is impossible to distinguish between different pairs of requests and responses (requestHash of the response does not really help because reconstruction of query is complicated and does not work with messages that had attachments).

Is there a better solution for that problem?

**Comment by margusf** [comment]
> Is there a better solution for that problem?

Well, one possible way is to attack the problem at the source. When designing the message protocol we proposed that the message IDs are generated by security server. This would have eliminated the problem of duplicated message IDs.

**Comment by PriitParmakson** [comment]
A provocative question: If client does not care (to ensure uniqueness of message id-s), why should we? 8)

**Comment by petkivim** [comment]
I think we should consider the point of view of the service provider as well: at the moment the client is responsible for generating a unique ID for the message and the service provider can't do anything else but hope that the client does so. From service provider's point of view it's not guaranteed that the message ID is unique. My point is that the client may not care about the message ID, while the service provider expects it to be unique. And this is a problem.

**Comment by PriitParmakson** [comment]
What is the business semantics of client sending two or more messages with the same ID? It's a violation of protocol but does it make one (or all?) of the messages void? Especially if service provider may have no practical method to check for uniqueness (and should he?).

Provision of unique ID-s on Security Server level, as Margus proposes, would load off the responsibility from client and help protect against theoretical replay attacks?

For comparison: Internet Message Format (e-mail) http://tools.ietf.org/html/rfc5322:
"every message SHOULD have a "Message-ID:" field. [..] The uniqueness of the message identifier is guaranteed by the host that generates it. [..] The message identifier (msg-id) itself MUST be a globally unique identifier for a message.  The generator of the message identifier MUST guarantee that the msg-id is unique." "if two messages have the same Message-ID, they are presumed to be the same one and one version is discarded." https://en.wikipedia.org/wiki/Message-ID.

**Comment by VitaliStupin** [comment]
I do not think that changing a protocol at this time would be a good idea. Also there is a slight chance that UUIDs generated by two independent Client Security Servers would be the same on the Producer side. And if we decide to change the protocol it must be a bulletproof solution.

Additionally we would need to make changes to error handling. For example if message ID was created in Clients Security server then we must always add that header to all soap faults returned to the client. Otherwise there might be a situation where Producer application logs request with a certain ID and the Client application does not know that ID.

There are also some not so radical alternatives:
- Adding a real-time unique check (can be a bad decision from the performance point of view)
- Making a hybrid solution where message id would be automatically filled with unique UUID if Client does not provide this value (it would still be a protocol change, but compatible with the 4.0). But this solution does not solve the problem where the Client is sending duplicate ID's.

**Comment by VitaliStupin** [comment]
One more solution to this problem:

We can add a "requestid" column to the table logrecord and all responses will point to the requests.
Signed document download service (http://SECURITYSERVER/asic) could use requestid to tie up request with response and for example add to their filenames the same suffix (queryId-response-Z.asice currently has a random "Z" component that could be the same for request/response pairs).
Archived message log must also use the same approach for naming of asice files (Z component is shared by request/response pairs).

That way we could always distinguish the request/response pairs without the need to change the protocol.

**Comment by margusf** [comment]
> Also there is a slight chance that UUIDs generated by two independent Client Security Servers would be the same on the Producer side. 

To quote wikipedia: "To put these numbers into perspective, the annual risk of a given person being hit by a meteorite is estimated to be one chance in 17 billion,[5] which means the probability is about 0.00000000006 (6 × 10−11), equivalent to the odds of creating a few tens of trillions of UUIDs in a year and having one duplicate."

So, properly generated UUIDs should be bulletproof for practical definition of "bulletproof".

> There are also some not so radical alternatives:
> - Adding a real-time unique check (can be a bad decision from the performance point of view)

Well, this is quite radical, given its impact to performance and overall dependency between message exchange and message logging.

Do I understand correctly that your last proposal basically means that security server will generate an identifier for a given transaction (request-response pair). This identifier is unique for all the transactions in this security server and different security servers can assign different identifiers for the same transaction. If so then this is IMO quite reasonable solution to the duplicate message ID problem.

**Comment by VitaliStupin** [comment]
Yes, my last proposal was to generate a request-response identifier that is unique for all the transactions in this security server and different security servers can assign different identifiers for the same transaction.

**Comment by hvainsalu** [comment]
Additional concern should be that we shouldn't tamper with the message. As the input was received from information system it must be signed and sent in the exact same way. Failing to do that would have the implication of "document being changed before signing." 
It need a well specified  series of hashes and algorithm how information system input is handled:
- receive input from information system
- calculate original hash.
- create UUID (or read it from the request) and add it to the message (response messages could be rejected in case of information system violation for using the same header).
- calculate secondary hash.
- sign the message
  All parties must be able to recalculate the whole scenario.

This kind of approach is currently violated by the "requestHash" element in the response messages.

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
