### ISSUE TITLE
As a Security Server Administrator I want crudini to be unbound from X-road packages and netcat to be removed

### ISSUE THREAD

**Issue by qrlt** [vrk-kpa/xroad-joint-development#212]
**Affected components**: -
**Affected documentation**: IG-CSHA
**Estimated delivery**: -
**External reference**: -

**Problem**
Script xroad_create_cluster.sh will install crudini and netcat in install_helper_tools() function. Netcat is unnecessarily big and too powerful for the tasks in cluster creating script(ex. checking the connection between nodes).
Crudini is bound to many X-road packages making the removal of crudini package without X-road packages a bit difficult.

**Acceptance criteria**
- Netcat to be replaced with ex. "netstat | grep 5432" or telnet
- Unbind crudini from X-road packages

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
