### ISSUE TITLE
As a Security Server Administrator I want that Apache CXF is upgraded to latest version so that known (possible) vulnerabilities are fixed

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#213]
**Affected components**: wsdlvalidator
**Affected documentation**: -
**Estimated delivery**: Q3/2018
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-1103

**Problem**
When running OWASP Dependency check -tool against the latest X-Road code base, tool is reporting some known and possible vulnerabilities related to Apache CXF component. Apache CXF is used in X-Road's wsdlvalidator package - this package provides services for the validation of WSDL files used in X-Road.

To fix the known vulnerabilities, Apache CXF component must be upgraded to latest version available. 
Apache CXF website (http://cxf.apache.org/) states that the latest version is v.3.2.2  During the upgrade work must be evaluated which version of Apache CXF is relevant to fix issues. Recommendation is to use the latest version. After upgrade work it is also most probably needed some migration work to get the wsdlvalidator package and the latest Apache CXF version to work together correctly. Migration work is included into the scope of this issue also.

Repository for X-Road wsdlvalidator is located here: https://github.com/ria-ee/wsdlvalidator
That repository must be upgraded to use the latest Apache CXF version. Repository must be updated so that it is possible to build and release a new version of wsdlvalidator package including all the needed fixes.

**Acceptance criteria**
- Apache CXF is upgraded to latest (or most suitable) version
- Migration work is completed to get wsdlvalidator package and latest(suitable) Apache CXF version to work together correctly
- Pull request is made to X-Road wsdlvalidator Github repository including to all needed (above listed) actions to complete upgrade work

**Comment by petkivim** [comment]
Transferred to NIIS backlog:

https://jira.niis.org/browse/XRDDEV-8
