### ISSUE TITLE
Generate Anchor file is wrong?

### ISSUE THREAD

**Issue by nguyenhabkit** [vrk-kpa/xroad-joint-development#217]
Hello everyone, I'm Ha and I'm a newbie in x-road.
As I followed the x-road central server install user guide and the x-road security server install user guide, I installed x-road center server and security server  successfully. But when I generate anchor file from the center server to upload from security server side  it's unsuccessful. This in content of the anchor file:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:configurationAnchor xmlns:ns2="http://x-road.eu/xsd/identifiers" xmlns:ns3="http://x-road.eu/xsd/xroad.xsd">
    <generatedAt>2018-04-02T04:11:52.254Z</generatedAt>
    <instanceIdentifier>nguyenha123</instanceIdentifier>
    <source>
        <downloadURL>http://10.145.35.109/internalconf</downloadURL>
        <verificationCert>MIICqTCCAZGgAwIBAgIBATANBgkqhkiG9w0BAQ0FADAOMQwwCgYDVQQDDANOL0EwHhcNNzAwMTAxMDAwMDAwWhcNMzgwMTAxMDAwMDAwWjAOMQwwCgYDVQQDDANOL0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4ne48Y1XGlaKmyNWztKcX2psK+gk2PdaEF33gksHm0Z8ZDmnetVc7nHjuRCi2X14LNHXglqt8WogL8ouvaCs4tK7pioGepCmBi0WAZDCKk77GRDEux5z7zqVxcbceRE/p0u06P1y1lPLxER8QPRp2phCvyMT4YlY7WBPv8gY67LKwrLesZ4MAEYY/InDm47M92aCpSpz8daze6kK8rlTe3qfh27mzphO9X4fa8Ci2bAxEE+IFhp3JDcJOm6gM9+tCC9pnj7+bSY3o8Ucp7uMc+v2NPLlDpFwRPthGsIuwcyaFXpgI3uglKWCheXCQUC/OeIxs0Q+0W/CBroVZmxnrAgMBAAGjEjAQMA4GA1UdDwEB/wQEAwIGQDANBgkqhkiG9w0BAQ0FAAOCAQEAhJNx5HQOjJaCxvuvm6+fEMWY1C+V7LqMd1FqgGH9QADp9N7hB663b1dJss0JkUMVwXb6x2B+6Tfd2zcGFonw0cnZdQ+IbVLgNKcRpLd1wHx7NOw3PT7z1yflmgseclp6sg+qyYJlsv48P7lc+Rmc0qQ3f6OnJ8jO6wFGTd6G7lAOJJWnXl5oh9mhplhMC0gtt44r6EtSxcZjQKiUlE0wnWNxT5ple6lK2INYRhjyD3JBNcFnQRhQ/+llJB50lUrF60uvU5Kh/SKV+kfhpSt7s9l5sMMGffLLw3VqB6wjRNM7+DgYEC4tWxOnX3d7BIMh8FfkaTnLg+5ff0JHymPBLA==</verificationCert>
    </source>
</ns3:configurationAnchor>

It's 404 error when I access link: http://10.145.35.109/internalconf
Please help me, what 's wrong is there?

**Comment by petkivim** [comment]
Hi Ha,

You're using a private IP address in the `downloadURL` element:

```
<downloadURL>http://10.145.35.109/internalconf</downloadURL>
```

Using a private IP is OK if ALL your security servers are in the same network with Central Server - you cannot access a private IP address over the Internet. If your security servers are in a different network and/or you need to be able to access global configuration over the Internet then the global configuration should be published using a public IP.

By the way, have you heard about the X-Road community? Check out the community site and join:

https://community.niis.org/

Regards,
Petteri

**Comment by nguyenhabkit** [comment]
Thanks for your answer, but I just access the address on my center server directly, and still 404 error.

**Comment by JyrgenSuvalov** [comment]
Do you have any error messages in the Central Server interface? Any ERROR messages in logs? What do /var/log/xroad/.global_conf_gen_status and /var/log/xroad/xroad_globalconf_signed-internalconf say?

**Comment by nguyenhabkit** [comment]
This is error message in the Central Server interface:
![xr-err](https://user-images.githubusercontent.com/37961023/38361481-b8fa1946-38f7-11e8-9b5e-a614ad4786af.png)
In /var/log/xroad/.global_conf_gen_status has just only 1 line : {"time":1522730221.525,"success":false}
And I don't see the file name: /var/log/xroad/xroad_globalconf_signed-internalconf, But I see the signer.log show many error in the attach file can you see it:
[signer.log](https://github.com/vrk-kpa/xroad-joint-development/files/1879680/signer.log)

**Comment by JyrgenSuvalov** [comment]
Have you completed all the requires steps mentioned in the user guide? https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#33-configuring-the-central-server-and-the-management-services-security-server.

It's likely you're missing some configuration elements that are required for generating the global configuration.

**Comment by nguyenhabkit** [comment]
You're right, I did not follow these steps carefully, I just only installed the central server and then generated the global configuration.
Thank you so much!
