### ISSUE TITLE
As a Security Server Administrator I want to be able to configure certain PKCS#11 module properties to support multithreading 

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#218]
**Affected components**: - hwtokens
**Affected documentation**: - ug-cp, ig-ss, ig-cs
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-406

**Problem**

One of our clients had some trouble with their HSM and multithreading. The remedy was changing the arguments (CKF_LIBRARY_CANT_CREATE_OS_THREADS and CKF_OS_LOCKING_OK) of pkcs11Module.initialize - https://github.com/ria-ee/X-Road/blob/develop/src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java#L73.

As a result we would like to make these arguments configurable in the devices.ini file.

**Acceptance criteria**
- CKF_OS_LOCKING_OK and CKF_LIBRARY_CANT_CREATE_OS_THREADS are configurable in the devices.ini file, default is null.
- Documentation is updated accordingly

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
