### ISSUE TITLE
Global configuration expired

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#219]
Hi everybody,

My nam is Hai. I am a newbie on X-Road. 
I have a problem when trying to generate sign certificate on security server. My SS announce that: Global configuration expired. I think it is the reason why I cannot use my certificate on central sever for registering as a member. Please let me know what I should do to solve this issue.

<img width="960" alt="screenshot_59" src="https://user-images.githubusercontent.com/12641471/38401357-72ed34b4-397f-11e8-9d6c-7aa151995941.png">

Regards,

Hai.

**Comment by JyrgenSuvalov** [comment]
Does your Central Server interface show any errors?

**Comment by hainguyen291** [comment]
It shows that: "Global configuration generation failing since ...".

**Comment by JyrgenSuvalov** [comment]
Are you logged into the token in the Central Server? Global Configuration view on the Central Server interface.

**Comment by egobsv** [comment]
This error usually shows up when your security server can not contact the central server. Make sure you have no red indicators in your diagnostics page and then check your logs (/var/log/xroad/signer.log and /var/log/xroad/proxy.log, etc. )

**Comment by hainguyen291** [comment]
Hi egobsv, 

I just reinstall security server on my computer. I have checked my diagnostics page and everything seems OK now.

![screenshot from 2018-04-09 15 49 24](https://user-images.githubusercontent.com/12641471/38488553-0cd13838-3c0e-11e8-8fdb-1a742c668d3e.png)

However, I don't know how to 

> To certify the authentication key, transmit the certificate signing request to the approved certification service provider and accept the authentication certificate created from the certificate signing 
request.>

Please take a glance on the above image to see my SS's states. Can you tell me how to send request to central server to becoming a member?

Best regards,

Hai

>

**Comment by hainguyen291** [comment]
Btw, I have tried to import certificate key as [import a certificate from the local file system](https://github.com/ria-ee/X-Road-EE-docs/blob/master/md/ug-ss_x-road_6_security_server_user_guide.md#313-importing-a-certificate-from-the-local-file-system). However, I always get this error

![screenshot from 2018-04-09 16 00 27](https://user-images.githubusercontent.com/12641471/38489152-bdb3c1ce-3c0f-11e8-94ff-8a63be4d0a9c.png)

The certificate file, which I used, is the one that I generated by doing like this [generating a certificate](https://github.com/ria-ee/X-Road-EE-docs/blob/master/md/ug-ss_x-road_6_security_server_user_guide.md#312-generating-a-certificate-signing-request-for-a-signing-key).

**Comment by TaaviMeinberg** [comment]
Hello Hai,

Once you have generated CSR files for sign and auth certificates (steps 3.1.2 and 3.2.2), please send them as attachments to: help@ria.ee . This way we can generate sign and auth certificates for you, using those CSR files.

**Comment by egobsv** [comment]
Hai,
I see that you are using EJBCA, are you trying to issue and validate your own certificates? 
The installation you have completed will only work withy certificates from RIA,  they will need to generate certificates for you as suggested in the previous post.

If you want to use your own PKI, you need to change the code and compile X-Road, we have documented the process here: https://github.com/egobsv/Tenoli-LAT (is in Spanish, but you can have the browser translate it for you.)  
Hope this helps,

**Comment by JyrgenSuvalov** [comment]
Yeah, the last screenshot indicates that Hai initialized a security server with our (RIA's) development environment's anchor. In which case Taavi's comment is valid :)

**Comment by hainguyen291** [comment]
Hi everyone,

Thank you for your supports. 

> If you want to use your own PKI, you need to change the code and compile X-Road, we have documented the process here

@egobsv : I am trying to create my own PKI, so I hope to have my own X-Road system. I will follow the process suggested by you. Thank you so much.

**Comment by hainguyen291** [comment]
@egobsv  I am learning to make my own X-Road system. So, it would be a big help if you can share some your related documents. I am very appreciated about that.

Best

**Comment by petkivim** [comment]
@hainguyen291 Are you setting up a test/development environment or a production system? If you're setting up a test/development environment and you're going to run your own CA (e.g. EJBCA), then you can use `EjbcaCertificateProfileInfoProvider`. It does not contain any hard coded values, the certificate profile defined by the class is:

`C`=`instanceIdentifier`
`O`=`memberClass`
`CN`=`memberCode`

In practice, if you want to use `VN` as your country code in the `C` field, you must set your X-Road instance's instance identifier to `VN` when you configure the Central Server. Unlike `FiVRKCertificateProfileInfoProvider` which contains the hard coded country code `C`=`FI`, `EjbcaCertificateProfileInfoProvider` does not contain any hard coded values.

In case your setting up a production environment  you need to have an implementation of the `CertificateProfileInfoProvider` interface that is aligned with your Certification Authority's certificate profile. That can be created using @egobsv's instructions. You can use the existing implementations as templates:

https://github.com/ria-ee/X-Road/tree/develop/src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl

**Comment by hainguyen291** [comment]
Hi @petkivim ,

I am going to setup a development environment.

**Comment by petkivim** [comment]
@hainguyen291 In that case the easiest alternative is to use one of the existing certificate profiles. You could set up your own instance of EJBCA and then use `EjbcaCertificateProfileInfoProvider`.  

Another alternative is to use an Ansible script available in the X-Road repository and use the openssl based test CA and TSA that are installed by the script. The test CA works with the Finnish certificate profile so you should use `FiVRKCertificateProfileInfoProvider` when you configure the central server. The country code `FI` is hard coded so you can not change it, but it should not matter in development environment.

The ansible script:
https://github.com/ria-ee/X-Road/tree/develop/ansible

Test CA:
https://github.com/vrk-kpa/X-Road/blob/develop/ansible/TESTCA.md

**Comment by hainguyen291** [comment]
@petkivim I have tried to install on [ virtual machine](https://github.com/ria-ee/X-Road/blob/develop/src/Vagrant.md) before . However, I got stuck at step 2: ./build_packages.sh. I will try again.
@egobsv I want to install 1 CS and 2 SS, so I follow [this tutorial](https://github.com/egobsv/Tenoli-LAT/blob/master/ubuntu-trusty/instalar-vagrant.md). I almost finished all these steps except this 
>
    Aplicar script de creación de maquinas virtuales (Vagrantfile). Este script usa la maquina tenoliBase para crear un servidor central (sc), dos servidores de seguridad (ss1 y ss2) y una autoridad certificadora (ca).

vagrant up

When I run "vagrant up"  command, I got error like this:
>hai@hainguyen:~/tenoli$ vagrant up
Bringing machine 'sc' up with 'virtualbox' provider...
Bringing machine 'ss1' up with 'virtualbox' provider...
Bringing machine 'ss2' up with 'virtualbox' provider...
Bringing machine 'ca' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* The following settings shouldn't exist: type

Could you please give me any suggestion about how to come over this one.

Thank you very much,

Hai

**Comment by petkivim** [comment]
@hainguyen291 Unfortunately, the instructions in the X-Road upstream repository are outdated.  An up-to-date version of the document is available at Finland's Population Register Centre's fork. The updated version is available at:

https://github.com/vrk-kpa/X-Road/blob/develop/src/Vagrant.md

The changes will be merged to the upstream repository.

**Comment by hainguyen291** [comment]
By removing "type" keywords from Vagrantfile, I can run though this step. However, I got a bunch of errors on they installation way

> dpkg: error processing package xroad-proxy (--configure):
 subprocess installed post-installation script returned error exit status 100
dpkg: dependency problems prevent configuration of xroad-addon-messagelog:
 xroad-addon-messagelog depends on xroad-proxy (>= 6.16.0); however:
  Package xroad-proxy is not configured yet.
> xroad-securityserver depends on xroad-addon-metaservices (>= 6.16.0); however:
  Package xroad-addon-metaservices is not configured yet.
 xroad-securityserver depends on xroad-addon-messagelog (>= 6.16.0); however:
  Package xroad-addon-messagelog is not configured yet.
 xroad-securityserver depends on xroad-addon-proxymonitor (>= 6.16.0); however:
  Package xroad-addon-proxymonitor is not configured yet.
 xroad-securityserver depends on xroad-addon-wsdlvalidator (>= 6.16.0); however:
  Package xroad-addon-wsdlvalidator is not configured yet.

> Errors were encountered while processing:
 xroad-proxy
 xroad-addon-messagelog
 xroad-addon-metaservices
 xroad-addon-proxymonitor
 xroad-addon-wsdlvalidator
 xroad-securityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
...

Do you have any idea about these errors?

**Comment by hainguyen291** [comment]
@petkivim Thank you so much!

**Comment by egobsv** [comment]
Hai, I have created an issue in our repository since the error you mentioned is related to what we have there: https://github.com/egobsv/Tenoli-LAT/issues/1
I will follow up with you there.
Regards,

**Comment by hainguyen291** [comment]
@petkivim 
>Unfortunately, the instructions in the X-Road upstream repository are outdated
>
But in this [guide](https://github.com/vrk-kpa/X-Road/blob/develop/src/Vagrant.md), I still see that we need to pull source code from this link git clone https://github.com/ria-ee/X-Road.git. Do you think I should use this one https://github.com/vrk-kpa/X-Road.git instead?

Thanks.

**Comment by petkivim** [comment]
@hainguyen291 

The X-Road master repository is https://github.com/ria-ee/X-Road.git which is why it is referenced in the instructions.

However, in this case it's better if you use https://github.com/vrk-kpa/X-Road.git to be sure that all the scripts are in line with the updated instructions.

**Comment by hainguyen291** [comment]
@petkivim I am follow the instruction and get error when tried to run this script
>./build_packages.sh

The errors are:
>FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

**Comment by hainguyen291** [comment]
@petkivim I tried to run this: ansible-playbook -i hosts/lxd_hosts.txt xroad_dev.yml. However, I still got errors

**Comment by hainguyen291** [comment]
vagrant@vagrant-ubuntu-trusty-64:~/X-Road/ansible$ ansible-playbook -i hosts/lxd_hosts.txt xroad_dev.yml

PLAY [lxd-servers] *****************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
ok: [localhost]

TASK [init-lxd : Ready all Ubuntu trusty containers] *******************************************************************************************
failed: [localhost] (item=xroad-lxd-ss1) => {"actions": [], "changed": false, "item": "xroad-lxd-ss1", "msg": "cannot connect to the LXD server"}
failed: [localhost] (item=xroad-lxd-ss2) => {"actions": [], "changed": false, "item": "xroad-lxd-ss2", "msg": "cannot connect to the LXD server"}
failed: [localhost] (item=xroad-lxd-cs) => {"actions": [], "changed": false, "item": "xroad-lxd-cs", "msg": "cannot connect to the LXD server"}
failed: [localhost] (item=xroad-lxd-ca) => {"actions": [], "changed": false, "item": "xroad-lxd-ca", "msg": "cannot connect to the LXD server"}
failed: [localhost] (item=xroad-lxd-cp) => {"actions": [], "changed": false, "item": "xroad-lxd-cp", "msg": "cannot connect to the LXD server"}
	to retry, use: --limit @/home/vagrant/X-Road/ansible/xroad_dev.retry

PLAY RECAP *************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by petkivim** [comment]
@hainguyen291 Were you able to solve the previous problem with the `build_packages.sh` script? And did you receive any errors when you executed `prepare_buildhost.sh` and `update_ruby_dependencies.sh`?

The error message that you're getting from Ansible indicates that the LXD server is not running. What happens when you issue `lxc list` command?

Which host OS are you using (the OS of your workstation where you run Vagrant and VirtualBox)?

**Comment by hainguyen291** [comment]
@petkivim I left the problem when running `build_packages.sh` to do next step `3. Setup LXD containers`
I didn't receive any errors when executing `prepare_buildhost.sh` or `update_ruby_dependencies.sh`

I got errors when run: `lxc list` due to `No command lxc found, did you mean...`

The OS that I am using is: ubuntu 14.0

**Comment by petkivim** [comment]
@hainguyen291 First you need the solve the problem with `build_packages.sh` and once that done you can move to the step 3.

How much memory (RAM) do you have on your host? And how much memory has been allocated to the Vagrant box? The problem with Gradle might be caused by insufficient memory. Host machine will need ~20GB free Storage and 4GB ram for virtual machine.

**Comment by hainguyen291** [comment]
@petkivim You are right, the above error is disappeared when I increase vagrant's RAM to 4GB. However, I got another error

>Execution failed for task ':center-service:warble'.
> Process 'command 'jruby'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':center-service:warble'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
>

Btw, `lxc list` command give me this result

>vagrant@vagrant-ubuntu-trusty-64:~/X-Road/src$ lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
>

**Comment by hainguyen291** [comment]
@petkivim I can run though step 3 already, even I still got errors from `./build_package.sh` script.

![screenshot from 2018-04-13 11 18 43](https://user-images.githubusercontent.com/12641471/38716730-78eae6e4-3f0c-11e8-92c1-e27ff6ce385b.png)

The list of server is shown bellow:

`vagrant@vagrant-ubuntu-trusty-64:~$ lxc list`

![screenshot from 2018-04-13 11 24 06](https://user-images.githubusercontent.com/12641471/38716862-35e034b6-3f0d-11e8-98b4-ecd66b01e191.png)

However, I still cannot access the CA or SS via browser:
- CA: https://10.193.132.98:4000
- SS1: https://10.193.132.180:4000

**Comment by petkivim** [comment]
@hainguyen291 Try to run gradle with --info or --debug options to get more information about the errors. You should be able to run `build_package.sh` script without errors. 

Can you increase Vagrant's RAM to 8 GB? According to the developers it would be better to have 8 GB when running the containers. If you cannot add more RAM, another alternative is to run less containers. The minimum setup you need for testing the X-Road is ca, cs and 2*ss. You can change the number of containers modifying this file:

https://github.com/vrk-kpa/X-Road/blob/develop/ansible/hosts/lxd_hosts.txt

**Comment by hainguyen291** [comment]
My computer is limited at 4GB RAM. So, I will eliminate CP and rh-ss1 containers. 
BTW, do I need to route ([step 4](https://github.com/vrk-kpa/X-Road/blob/develop/src/Vagrant.md#4-access-x-road-from-host))  to access CA, SS via browser?

**Comment by petkivim** [comment]
Yes, step 4 is needed to access services running in the containers via browser.

**Comment by hainguyen291** [comment]
@petkivim I've tried to do step 4

![screenshot from 2018-04-13 14 34 00](https://user-images.githubusercontent.com/12641471/38722342-dda0f4fa-3f27-11e8-894f-fd47c5479e98.png)

However, It seems that I use wrong ip address, that is why I cannot connect to CA or SS from browser. 
Information about my route table and ip address are mentioned on the above image. Please let me know if I did something wrong.
` sudo ip route add 10.145.35.0/24 via 10.193.132.244`

Regards,

Hai

**Comment by hainguyen291** [comment]
Do you have any idea about above route table? What should I changed to make it run on web browsers?

**Comment by petkivim** [comment]
@hainguyen291 The route should be added on the host computer, not inside the Vagrant box. Try adding the route on the host.

**Comment by hainguyen291** [comment]
ifconfig
![screenshot from 2018-04-16 17 03 05](https://user-images.githubusercontent.com/12641471/38802998-13ba1252-4198-11e8-869a-e0921dfc2734.png)

this is servers on my vagrant machines
![screenshot from 2018-04-16 17 03 35](https://user-images.githubusercontent.com/12641471/38803012-1ff5f0c2-4198-11e8-9fd9-a3a3168b2c86.png)

Then, I tried this command from the host: sudo ip route add 10.193.132.0/24 via 10.145.35.115
However, I haven't accessed to this machines yet! Did I do something wrong?

**Comment by petkivim** [comment]
The Vagrant file should create one host-only network (vboxnet3 or something similar, IP 10.122.151.0/24) and for some reason it's not there. The route must be created via the IP of the virtual machine in that network which is static `10.122.151.3`. 

`ip route add 10.122.150.0/24 via 10.122.151.3`

Something has gone wrong at some point, because the network is not there.

**Comment by hainguyen291** [comment]
@petkivim I have reinstall with the repository downloaded on ria-ee. Everything steps are run smoothly, even ./build_package.sh step. Here is my `lxc list`

![screenshot from 2018-04-17 16 38 29](https://user-images.githubusercontent.com/12641471/38861983-004804c4-425e-11e8-82b3-29fa9b5a6a36.png)

I also can `ping 10.152.47.227`. So, do I need to route/implement [step 4](https://github.com/ria-ee/X-Road/blob/develop/src/Vagrant.md#4-access-x-road-from-host)? 

P/S: Even I still install servers via LXD, I installed X-Road directly on my computer instead of vagrant machines.

**Comment by petkivim** [comment]
@hainguyen291 Great that you got it working. You have installed the lxd containers on your host without Vagrant so you can skip step 4.

Have you tried the access the UIs? They should be accessible using the URLs below:

CS: https://10.152.47.227:4000
RH-SS1: https://10.152.47.121:4000
SS1: https://10.152.47.14:4000
SS2: https://10.152.47.61:4000

**Comment by hainguyen291** [comment]
@petkivim I tried to access https://10.152.47.227:4000/ but it didn't work. As you can see on the above picture, I tried to `telnet 10.152.47.227` but I unable to connect to it (Even though : `telnet 10.152.47.277 4000` also didn't work). I don't know why. Do you have any ideas about that?

**Comment by hainguyen291** [comment]
Even though I can ping to these IP address, they are still different from IP range of my computer. My computer IP is: 10.145.35.1 mean while, virtual machines's IP are 10.152.47.1

![screenshot from 2018-04-18 09 30 28](https://user-images.githubusercontent.com/12641471/38908665-81fed578-42eb-11e8-8c78-3a02d42cce8c.png)

**Comment by petkivim** [comment]
@hainguyen291 You shouldn't need to configure routes as the containers are running on your host. Have you checked if the services are running inside the containers? You can access the containers as `root` using this command:

`lxc exec <containername> bash`

It might be that the required services inside the containers are not running even if the containers are running. This would explain why ping is responding, but the X-Road services are not.

You could also consider stopping the containers that you don't need: `cp`, `rh-ss1`. One reason for the problems might be insufficient memory - 4 GB might not be enough for running all the containers.

**Comment by hainguyen291** [comment]
Here is my services inside lxd-cs container.

![screenshot from 2018-04-18 14 31 18](https://user-images.githubusercontent.com/12641471/38917504-2e3194e2-4315-11e8-9c37-56bd23aebeab.png)

Which one is the cs services that I should start?

**Comment by petkivim** [comment]
What's the output of this command?

`dpkg -l | grep xroad-`

**Comment by hainguyen291** [comment]
This is the output of this command on both my machine and cs container

nguyenha@nguyenha:~/xroad$ dpkg -l | grep xroad-
nguyenha@nguyenha:~/xroad$ lxc exec xroad-lxd-cs bash
root@xroad-lxd-cs:~# dpkg -l | grep xroad-
root@xroad-lxd-cs:~# 

It seems that for some reasons, there are no x-road services run on my computer. I have followed [this instruction](https://github.com/vrk-kpa/X-Road/blob/develop/src/Vagrant.md) carefully without any errors. I think I need to try again, don't I?

**Comment by petkivim** [comment]
@hainguyen291  It's enough to run the command inside the LXD container. The output of `dpkg -l | grep xroad-` should look like this. The version number might be different, but all these packages should be installed on the `xroad-lxd-cs` container. 

```
root@ip-10-4-0-97:/home/ubuntu# dpkg -l | grep xroad-
ii  xroad-center                     6.16.0-1                                   all          X-Road central server
ii  xroad-centralserver              6.16.0-1                                   all          X-Road central server
ii  xroad-centralserver-monitoring   6.16.0-1                                   all          Monitoring client configuration for X-Road central
ii  xroad-common                     6.16.0-1                                   amd64        X-Road shared components
ii  xroad-jetty9                     6.16.0-1                                   all          Jetty9 for X-Road purposes
```

Running services can be checked using `initctl list | grep "^xroad-"` command. The output should look like this.

```
root@ip-10-4-0-97:/home/ubuntu# initctl list | grep "^xroad-"
xroad-jetty start/running, process 1063
xroad-confclient stop/waiting
xroad-signer start/running, process 1064
```

For some reason the packages are not there. This means that some step(s) has failed during the build process. I know that the output is very verbose, but you should try to locate any errors that would explain why the packages are missing.

**Comment by hainguyen291** [comment]
Thanks @petkivim for your supports. I will start the beginning to install X-Road. Thanks for your patient.

**Comment by hainguyen291** [comment]
Hi @petkivim . I have installed my own X-Road.

>@hainguyen291 In that case the easiest alternative is to use one of the existing certificate profiles. You could set up your own instance of EJBCA and then use EjbcaCertificateProfileInfoProvider.

Based on your suggestion, when should I use EjbcaCertificateProfileInfoProvider to config my central server?

Further more, I am trying to [adding an approved cetrification service](https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#111-adding-an-approved-certification-service) to my central server. However, I don't know how to locate the certification service CA file as instruction.

Best regards,

Hai

**Comment by petkivim** [comment]
Hi @hainguyen291,

You should use `EjbcaCertificateProfileInfoProvider` if you have implemented your certification service using EJBCA. In addition, you can use it with any other certificate provider that accepts the certificate profile defined by the `EjbcaCertificateProfileInfoProvider` class:

C=instanceIdentifier
O=memberClass
CN=memberCode

I noticed that you opened another issue (#225) regarding adding an approved certification service to central server. I posted my answer to that question there.
