### ISSUE TITLE
As an x-road administrator, I want to be able to manage the security server via an API

### ISSUE THREAD

**Issue by andreskytt** [vrk-kpa/xroad-joint-development#22]
Currently the security server can be managed by a tightly integrated configuration UI. This is limiting in many ways. Instead, the security server should provide a reasonable API the UI could utilise and that could also be used for automation. This would also mean re-implementing the UI to use the new API

The API should 
- be secured to prevent unauthorised configuration updates. For example, the API could be comprised of an agreed location of a signed configuration file of a stable structure
- treated as an external interface to the security server and documented/managed accordingly
- encapsulate all interaction between the UI and the x-road infrastructure including between UI and the central server

The UI should
- Allow for external authorisation and authentication providers to be plugged in

**Comment by petkivim** [comment]
Transferred to NIIS backlog:

https://jira.niis.org/browse/XRDDEV-110
