### ISSUE TITLE
Bug: Support for TLS1.1 does not actually work - documentation needs to be updated

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#220]
**Affected components**: - xroad-proxy
**Affected documentation**: - ug-sysparams
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-411

**Problem**
Jetty9 has a list of excluded ciphers which exclude support for SHA1 ciphers, therefore TLS1.1 is not actually supported, even if you configure client-tls-ciphers and client-tls-protocols to use it.

`setExcludeCipherSuites("^.*_(MD5|SHA|SHA1)$");`

We could make the exclusion list configurable to allow support for TLS1.1, but it's excluded for a reason, so we should just rather update the documentation and code.

**Acceptance criteria**
- TLS1.1 and SHA1 ciphers are removed from ug-sysparams and code

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
