### ISSUE TITLE
Bug: Global configuration files in the central server are not written in an atomic way

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#221]
**Affected components**: - xroad-centralserver
**Affected documentation**: - 
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-314

**Problem**
The central server does not write global configuration files in an atomic way. Because of this, sometimes the signer tries to read the configuration files while the global configuration generator is still writing them, resulting in an error:

`/var/log/xroad/signer.log:2017-01-10 12:31:12,947 ERROR [Signer-akka.actor.default-dispatcher-14] e.r.x.c.c.g.GlobalConfProviderFactory - Could not create an instance of GlobalConfProvider!`

**Acceptance criteria**
- Global configuration files in the central server need to be written in an atomic way.

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
