### ISSUE TITLE
Bug: sending-interval-seconds parameter's description is misleading

### ISSUE THREAD

**Issue by JyrgenSuvalov** [vrk-kpa/xroad-joint-development#222]
**Affected components**: - N/A
**Affected documentation**: - ug-opmonsyspar
**Estimated delivery**: -
**External reference**: - https://jira.ria.ee/browse/XTE-409

**Problem**
The current description of op-monitor-buffer.sending-interval-seconds is misleading. The current description says:

"The interval in seconds at which the operational monitoring buffer tries to send records to the operational monitoring daemon."

Actually, this is the interval for RETRYING to send the records.

**Acceptance criteria**
- ug-opmonsyspar document is updated with a better explanation of the parameter

**Comment by VitaliStupin** [comment]
Fixed in 6.18.0
