### ISSUE TITLE
Adding an Approved Certification Service

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#225]
Hi everyone,

I am trying to create a [certification service](https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#111-adding-an-approved-certification-service) from central server. However, I don't know how to find a file like this `Locate the certification service CA certificate file and click Next.`. When do we have this file before this step?

Regards,

Hai.

**Comment by hainguyen291** [comment]
Are they one of the files on this link?

https://github.com/ria-ee/X-Road/tree/develop/src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl

**Comment by petkivim** [comment]
Hi @hainguyen291,

Certification service / certification authority is an external service that is not part of the X-Road software. Please see the [system architecture](https://github.com/ria-ee/X-Road/blob/develop/doc/Architecture/arc-g_x-road_arhitecture.md#2-system-components) document for more detailed information about the [role of the  certification authority](https://github.com/ria-ee/X-Road/blob/develop/doc/Architecture/arc-g_x-road_arhitecture.md#25-certification-authority).

For testing purposes you can set up your own CA using some open source component, e.g. [EJBCA](https://www.ejbca.org/) or openssl based [test CA](https://github.com/vrk-kpa/X-Road/blob/develop/ansible/TESTCA.md) that's available on the X-Road GitHub repository. For production environment it's recommended to use a trusted certification authority. 

Creating a certification service to the central server means that you must upload the root certificate of the CA that you're using to the central server and define the URL of the OCSP service provided by the CA. 

Another external service that you need for running an X-Road instance is a time-stamping service / time-stamping authority.

**Comment by hainguyen291** [comment]
Hi @petkivim 

I am trying to deploy openssl based test CA. However, when I run `init.sh` script, undered `ca`, I got this error:

![screenshot from 2018-05-08 10 15 44](https://user-images.githubusercontent.com/12641471/39736124-f752493c-52a8-11e8-9e32-8a494e229e7d.png)

I keep all default value for these parameters (didn't edit anything):

># dn parameters
DN_COUNTRY="{{ xroad_ca_dn_country }}"
DN_CA_O="{{ xroad_ca_o }}"
DN_CA_OU="{{ xroad_ca_ou }}"
DN_CA_CN="{{ xroad_ca_cn }}"
DN_OCSP_O="{{ xroad_ca_ocsp_o }}"
DN_OCSP_OU="{{ xroad_ca_ocsp_ou }}"
DN_OCSP_CN="{{ xroad_ca_ocsp_cn }}"
DN_TSA_O="{{ xroad_ca_tsa_o }}"
DN_TSA_OU="{{ xroad_ca_tsa_ou }}"
DN_TSA_CN="{{ xroad_ca_tsa_cn }}"
>

**Comment by hainguyen291** [comment]
@petkivim I found out the error due to country code is longer than 2 characters. So, I edit 
DN_COUNTRY="vn"
And run script successfully. 

However, I got problem when try to use `EjbcaCertificateProfileInfoProvider`, same problem to FiVRKCertificateProfileInfoProvider, as provider.

![screenshot from 2018-05-08 10 48 51](https://user-images.githubusercontent.com/12641471/39737093-8f05c32c-52ad-11e8-8ccb-c23a3b35c2cb.png)

How can I solve this problem?

Regards
Hai

**Comment by hainguyen291** [comment]
It is my bad, I should add full path of this provider instead of its name.
`ee.ria.xroad.common.certificateprofile.impl.EjbcaCertificateProfileInfoProvider` sloved my problem

**Comment by hainguyen291** [comment]
Hi @petkivim ,

I tried to sign AUTH and SIGN certificate via test-CA server based on this [instruction](https://github.com/vrk-kpa/X-Road/blob/develop/ansible/TESTCA.md#71-use-command-sign-on-a-file), but I didn't make it. 

>hai@hai:~$ sudo sign auth_csr_20180508_securityserver_VN_HAI_ss_ss.pem
>sudo: sign: command not found
>hai@hai:~$ su - ca
>Password: 
>ca@hai:~$ sign auth_csr_20180508_securityserver_VN_HAI_ss_ss.pem
>-su: /usr/local/bin/sign: Permission denied
> ca@hai:~$
