### ISSUE TITLE
URL for Timestamping Service

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#227]
Hi everyone,

I create my own xroad instan. So, When I uploaded a tsacert.pem on central server, it asked me to give url. How can I get this URL?

![screenshot from 2018-05-09 16 44 01](https://user-images.githubusercontent.com/12641471/39808148-60e4c2f8-53a8-11e8-812c-7c43d25842dc.png)

Thanks,
Hai.

**Comment by petkivim** [comment]
Hi @hainguyen291,

I assume that you're using the test CA setup described [here](https://github.com/vrk-kpa/X-Road/blob/develop/ansible/TESTCA.md). The TSA service is running in port `8899` so the URL is `http:/{PRIVATE_IP_OF_YOUR_TSA_HOST}:8899`. The private IP is probably `10.145.12.XXX` based on the IP of the central server.

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim ,

Thanks for your suggestion, I can find out the url :+1: . I use the same IP for OCSP with port 8888, but It seems there are something wrong with my [OCSP](https://github.com/vrk-kpa/xroad-joint-development/issues/226#issuecomment-388014793). I will close this topic and follow with you at the other.

Regards,
Hai.
