### ISSUE TITLE
EJBCA Certificate

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#232]
Hi everybody,

I am using my own ejbca certificate to add to Certificate services on Central Server. However, I couldn't use singed certs, which were sent from Security Server to ejbca CA server to be signed, to import to SS. I always get error 

audit.log
================
> 2018-05-24T09:43:59+07:00 ss INFO  [X-Road Proxy UI] 2018-05-24 09:43:59+0700 - {"event":"Import certificate from file failed","user":"ss","reason":"Certificate is not valid","data":{"certFileName":"ss(1).pem","certHash":"25:96:06:86:75:71:78:F7:84:68:4C:45:01:65:47:63:4F:2E:C6:B9","certHashAlgorithm":"SHA-1","keyUsage":"AUTHENTICATION"}}
================
<img width="958" alt="screenshot_62" src="https://user-images.githubusercontent.com/12641471/40463105-6b17abaa-5f3d-11e8-9e8d-e65c188cedaa.png">

Are there anything I need to do with my EJBCA CA before use it to sign certs? 
Regards,
Hai

**Comment by JyrgenSuvalov** [comment]
Hello Hai,

Can you post the certificates you're using? I.e the CA cert you're using in the central server, the intermediate certificate (if you're using one) and the sign certificate you're trying to import. I think the exception comes from being unable to verify the certificate chain.

Information about your EJBCA end entities would also be helpful, I suppose.

As far as EJBCA is concerned, our capability to support it here is somewhat minimal, but we'll try to help :)

**Comment by hainguyen291** [comment]
Hi @JyrgenSuvalov

Attached files are my ocsp.pem file, which I used for Certificate Services on central server. I don't use intermediate certificate.
The two others are my sign and auth certificates, which I sent to CA server to request.
[cert.zip](https://github.com/vrk-kpa/xroad-joint-development/files/2037834/cert.zip)

Btw, are there any instruction to install X-Road via source code downloaded from github?

Thanks,
Hai

**Comment by hainguyen291** [comment]
@JyrgenSuvalov Do you need more information about this EJBCA? 

Regards,
Hai

**Comment by JyrgenSuvalov** [comment]
@hainguyen291 Sorry I haven't replied. I'm afraid I'm currently really not able to provide much help, since I don't have access to an EJBCA myself at the moment.

There's an overview of EJBCA and using it with X-Road here: https://www.auul.pri.ee/wiki/EJBCA_CA_haldamine#X-tee_turvaserveri_sertifikaatide_haldamine (it's in Estonian, but Google translate should help). It's not a quick start guide however.

**Comment by hainguyen291** [comment]
@JyrgenSuvalov Thanks for your support.

Best,
Hai

**Comment by petkivim** [comment]
If the problem still persists, please open a new issue in the [X-Road Development](https://github.com/nordic-institute/X-Road-development/issues) repository.

Regards,
Petteri
