### ISSUE TITLE
Cannot start SS services

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#233]
Hi everyone,

I just installed new SS. However, I cannot start any services. Please give me a hand.

![image](https://user-images.githubusercontent.com/12641471/43947323-fc9b0944-9cb1-11e8-92d6-42a51e56e30c.png)

Thanks,
Hai

**Comment by hanhaka** [comment]
Hi,

please note that this repository is now replaced by a new one. See the main page information: 'Unmaintained repository. Development moved to: https://github.com/nordic-institute/X-Road-development'.

Write down this issue to the repository mentioned above to get help.

Thanks,
Hannu

**Comment by hainguyen291** [comment]
Thank you so much.
