### ISSUE TITLE
Cannot connect to TSA/OCSP servers

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#234]
Hi everyone,

I build test CA servers including: TSA and OCSP. However, status of TSA and OCSP on SS's side is always in yellow `service has been contacted but is yet to have been used to verify its status` state. 

![image](https://user-images.githubusercontent.com/12641471/45086159-c36a4880-b12c-11e8-9d9b-bbf0457c83d9.png)
What should I do now?

Regars,
Hai

**Comment by hainguyen291** [comment]
Here is the `signer.log` of my Security Server.

![image](https://user-images.githubusercontent.com/12641471/45097971-37691880-b14e-11e8-94f5-01aa77827a38.png)

And this is certificate that I am using for test-CA and the log of /upstart/ocsp.log

![image](https://user-images.githubusercontent.com/12641471/45098025-5bc4f500-b14e-11e8-9820-fb2e86d95b43.png)

![image](https://user-images.githubusercontent.com/12641471/45098178-a47cae00-b14e-11e8-9422-b417ca184eaa.png)

**Comment by petkivim** [comment]
Hi @hainguyen291 

Does the Security Server have auth and/or sign certificates yet? The Security Server tries to connect the OCSP service only if it has certificates which OCSP responses must be fetched. Time-stamping takes place only when messages are processed so if you haven't sent any messages TSA should not be connected either. 

If there are no certificates configured yet and no messages have been sent, that's the expected status.

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi petkivim,

You are right. It is my bad!!! It has been 3 months since the last time I config SS, I almost forget this step. Btw, I am going to build a HA system for Security Server Clustering. Are there any documents about this?

Thank you very much,
Hai

**Comment by JyrgenSuvalov** [comment]
Hi @hainguyen291 

I think Petteri's blog post on load balancing provides a very good overview of HA in X-Road :)
https://www.niis.org/blog/2018/6/25/balancing-the-load.

Regards,
Jürgen

**Comment by hainguyen291** [comment]
Hi @JyrgenSuvalov 

Thank you,
Hai
