### ISSUE TITLE
Certificate Registry

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#235]
Hi @petkivim ,

I am going to send registry request from Security Server to Central Server as image below.

![image](https://user-images.githubusercontent.com/12641471/45213337-75d31480-b2c1-11e8-8038-19be36ca8682.png)

However, I got error `Failed to register certificate: Member 'MEMBER:XROADVN/GOV/VPCP03' has no suitable certificates` when tried to registry with public IP: 10.0.5.133, **which is NAT** via firewall to 10.9.32.86. 

![image](https://user-images.githubusercontent.com/12641471/45212397-fe03ea80-b2be-11e8-8057-0f50f0d02cbb.png)

10.9.32.86 is my internal IP, meanwhile 10.0.5.133 is its public IP. I can access this computer via internal IP via VPN as you see on the image. I tried both internal IP and public IP to send registry request but all are failed. Please let me know what I should to do now?

Best regards,
Hai

**Comment by hainguyen291** [comment]
`TCP 80, 443 - Ports for outbound connections (from the security server to the external network)
Most common OCSP and time-stamping services`

Do I need to open firewall for ports 80 and 443?

**Comment by petkivim** [comment]
Hi @hainguyen291 

It seems that the Security Server hosting the Management Services does not have a valid certificate yet. You're trying to register a certificate for a Security Server which server code is `VPCPSS03` and the error message says that server `VPCP03` has no suitable certificates. First you must complete the configuration of `VPCP03` and only after that you can register more Security Servers. Please check that you have completed steps 1-12 in section 3.3:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#33-configuring-the-central-server-and-the-management-services-security-server

All 10.* IP addresses are private so you cannot have public IPs in that IP range.

https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses

Regards,
Petteri

**Comment by petkivim** [comment]
> Do I need to open firewall for ports 80 and 443?

If OCSP and TSA are running on those ports in an external network, then outgoing network connections must be allowed from Security Server.

**Comment by hainguyen291** [comment]
Hi @petkivim 

I am using VPCPSS as security server hosting management services.

![image](https://user-images.githubusercontent.com/12641471/45223539-bc386b80-b2e1-11e8-95f0-177bbcbe4fa0.png)

![image](https://user-images.githubusercontent.com/12641471/45223557-c9edf100-b2e1-11e8-86de-c1640a672ca5.png)

By doing like this, I have registered SS01 successfully 

![image](https://user-images.githubusercontent.com/12641471/45223643-fb66bc80-b2e1-11e8-8376-07e875a685b8.png)

My OCSP and TSA are running on ports 8888 and 8899.

**Comment by petkivim** [comment]
Does `VPCPSS03` have a sign certificate?

**Comment by petkivim** [comment]
> My OCSP and TSA are running on ports 8888 and 8899.

You must allow outgoing traffic to ports 8888 and 8899.

**Comment by hainguyen291** [comment]
VPCPSS03 has sign certificate already

![image](https://user-images.githubusercontent.com/12641471/45225943-e7be5480-b2e7-11e8-9fa9-2cbb9a67299f.png)

**Comment by hainguyen291** [comment]
Do you mean outgoing traffic of public IP 10.0.5.133 NAT via firewall to 10.9.32.86 or 10.9.32.86 itself?
Although 10.9.32.86 is belonged to private network, but we still can use public IP (10.0.5.133) to NAT via firewall and router to .86 because our CS is also at the same network.

**Comment by hainguyen291** [comment]
123.31.27.101 is public IP, but internal IP of this one is 10.0.14.227. This is our CA server, where we deployed OCSP and TSA server too.

**Comment by petkivim** [comment]
OCSP status of the sign certificate is unknown - that's the reason why the request fails. You should wait that the status is good.

**Comment by hainguyen291** [comment]
Here is .86's diagnostic 

![image](https://user-images.githubusercontent.com/12641471/45226703-ce1e0c80-b2e9-11e8-829a-d866fe790451.png)

And it seems that my OCSP `http://10.0.14.227:8888` is in good state, doesn't it?

**Comment by hainguyen291** [comment]
> You should wait that the status is good.

Do I need to do something with OCSP or just wait until status is good?

**Comment by hainguyen291** [comment]
Should I remove SS on .86 and reinstall it again?

**Comment by petkivim** [comment]
You should make sure that all the security servers have access to OCSP and TSA host's ports 8888 and 8899. Which IP you should use depends on the routing in your network. If all the hosts are in the same network the private IP should probably work (if you don't have any host level firewall that's blocking connections).

**Comment by petkivim** [comment]
You have two OCSP responders there and the status of the first one is red. The first one uses the public IP and the second one the private IP. The Security Server is probably trying to connect the first one which is not accessible at the moment. You could try to remove the first one from configuration as the second one is working. That should solve the problem.

**Comment by hainguyen291** [comment]
I did remove the first one and keep the working one. 

![image](https://user-images.githubusercontent.com/12641471/45230486-33c2c680-b2f3-11e8-8226-c1a77f3b0d82.png)

However, my sign certificate status still be unknown

![image](https://user-images.githubusercontent.com/12641471/45230540-5d7bed80-b2f3-11e8-9194-a8169a093a5a.png)

The .86 is behind a firewall, that's why we need to connect via `10.0.5.133` as public IP in this private network. My CS can ping and telnet to `10.0.5.133`

![image](https://user-images.githubusercontent.com/12641471/45230632-a16ef280-b2f3-11e8-96a2-07ef67bfef45.png)

And my .86 can ping and telnet to my CS server, whose private IP is `10.0.14.227`

**Comment by hainguyen291** [comment]
I think that, the ocsp response status is unknown because of .86 cannot get response from .227 (OCSP servers). As we know that, .86 is behind a firewall, which we can only access inbound via .133. Once OCSP server gets a request from .86 (outbound), so It should give a response back to .86 instead of .133 ( it even doesn't know exist of .133). However, we cannot access inbound directly to .86 without going through .133, that is why .86 don't get any response from OCSP.

`Unknown (validity information missing) – the certificate does not have a valid OCSP response (the OCSP response validity period is set by the X-Road governing authority) or the last OCSP response was either “unknown” (the responder doesn't know about the certificate being requested) or an error.`

So, I think we should customize OCSP server, don't we? Do you have any resolution for this problem?

Best,
Hai

**Comment by petkivim** [comment]
I think that there's no need to customize the OCSP service. The problem should be solved updating the network and/or firewall configuration.

> And my .86 can ping and telnet to my CS server, whose private IP is 10.0.14.227

Are you able to ping from .86 to .227 ports 8888 and 8899?

Is your firewall stateful or stateless? In case it's stateful, it's enough to allow outbound connections from .86 to .227:8888 and .227:8899. In case it's stateless, in addition to outbound connections, on .86 you must also allow inbound connections to ephemeral ports (1024-65535) from .227.

**Comment by hainguyen291** [comment]
I can telnet from .86 to .227 via ports 8888 and 8899

![image](https://user-images.githubusercontent.com/12641471/45251915-6b278680-b378-11e8-9e5b-b232d611b611.png)

However, I cannot ping from .227 to .86 directly. I need pass by .133, which is NAT via firewall to .86. Is this the reason why OCSP server response, which serve for .86 request, cannot reach .86?

**Comment by petkivim** [comment]
> I can telnet from .86 to .227 via ports 8888 and 8899
> However, I cannot ping from .227 to .86 directly.

Requests are always initiated by .86 (.86 => .227) so direct access from .227 to .86 should not be required. 

Is the OCSP service working properly on your other Security Servers at the moment? The only one that has problems is .86? Just to be sure, because based on your tests using telnet the connections should work.

**Comment by hainguyen291** [comment]
Yes, it works with SS .104. And I used .104 as SS host management services

![image](https://user-images.githubusercontent.com/12641471/45252719-cf047c00-b385-11e8-9803-5316e5bf7e71.png)

![image](https://user-images.githubusercontent.com/12641471/45252723-e0e61f00-b385-11e8-8519-7e7426bf731f.png)

**Comment by hainguyen291** [comment]
@petkivim 

I disable firewall on .227 and it suddenly works like magic???

![image](https://user-images.githubusercontent.com/12641471/45253125-fcecbf00-b38b-11e8-8cda-64c3441e6a6b.png)

I haven't had exactly answer, however the most important thing is it is working now. 
Thanks for your support, my friend.

Hai

**Comment by petkivim** [comment]
Great, that you got it working! :) The firewall might have blocked the response messages for some reason. It might be worth checking is the firewall stateful or stateless, and check the access rules after that.

> Is your firewall stateful or stateless? In case it's stateful, it's enough to allow outbound connections from .86 to .227:8888 and .227:8899. In case it's stateless, in addition to outbound connections, on .86 you must also allow inbound connections to ephemeral ports (1024-65535) from .227.

**Comment by petkivim** [comment]
By the way, please submit your support requests to our current repository from now on:

https://github.com/nordic-institute/X-Road-development/

This repository is not used anymore.

**Comment by hainguyen291** [comment]
I got it @petkivim . Thank you.
