### ISSUE TITLE
Setting up a local X-Road instance with errors

### ISSUE THREAD

**Issue by yamatokataoka** [vrk-kpa/xroad-joint-development#236]
Hello @petkivim,

My name is Yamato. I am a newbie on X-Road.

I have a problem when trying to set up a build environment and a local X-Road instance using Vagrant.

I've followed [the instruction](https://github.com/vrk-kpa/X-Road/blob/develop/src/Vagrant.md#4-access-x-road-from-host) and gotten error when tried to run this script

`ansible-playbook -i hosts/lxd_hosts.txt xroad_dev.yml`

<img width="1280" alt="screen shot 2018-09-08 at 23 19 55" src="https://user-images.githubusercontent.com/34284486/45255167-21618f00-b3be-11e8-98a6-58d9d9aac3f5.png">

also, 

<img width="1280" alt="screen shot 2018-09-08 at 23 23 50" src="https://user-images.githubusercontent.com/34284486/45255195-40f8b780-b3be-11e8-9b3c-dc0ff06c0296.png">

I didn't receive any errors when executing `prepare_buildhost.sh` or `update_ruby_dependencies.sh`

And `lxc list` command seems work well.

However, I couldn't access the CA or SS via browser:

- CA: https://10.122.150.50:4000
- SS1: https://10.122.150.206:4000
- SS2: https://10.122.150.59:4000

Regards,

Yamato

P/S: The OS that I am using is: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64) on a virtual machine
and, the OS of my host machine is: macOS

**Comment by petkivim** [comment]
Hi @yamato-k 

This repository is not used anymore, please submit your support requests to our current repository next time:

https://github.com/nordic-institute/X-Road-development/

Current X-Road master repository is:

https://github.com/nordic-institute/X-Road

This repository is not maintained anymore:

https://github.com/vrk-kpa/X-Road/

Did you already build the packages (`./build_packages.sh`) successfully before running the Ansible script? If yes, try to run the Ansible script with `--skip-tags "compile"` switch. By default, the script build the packages first, but that part can be skipped if you have already run `./build_packages.sh` manually.

`
ansible-playbook -i hosts/lxd_hosts.txt xroad_dev.yml --skip-tags "compile"
`

When have you cloned and last synced (`git pull`) the X-Road master repository (https://github.com/nordic-institute/X-Road)? If you have cloned the repository earlier and not synced it recently, please sync it first and then try to compile & install again. Earlier there was a problem with packaging that has been fixed recently. If you have cloned VRK's X-Road repository (https://github.com/vrk-kpa/X-Road/) then switching to the current master repository (https://github.com/nordic-institute/X-Road) will fix the problem.

Regards,
Petteri

**Comment by yamatokataoka** [comment]
Thank you for your help.

I synced new repository again, then fixed the problem.
