### ISSUE TITLE
xroad secruity server install problem

### ISSUE THREAD

**Issue by mdgaffar** [vrk-kpa/xroad-joint-development#237]
**Affected components**: - xroad secruity server
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
While installing xroad security server in Ubuntu 14.04 LTS, getting dependency error.

# apt-get install xroad-securityserver
.......
.......
The user `xroadx' is already a member of `xroad-securityserver-observer'.
stop: Unknown job: rsyslog
start: Unknown job: rsyslog
dpkg: error processing package xroad-proxy (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of xroad-addon-messagelog:
 xroad-addon-messagelog depends on xroad-proxy (>= 6.16.0); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-messagelog (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-metaservices:
 xroad-addon-metaservices depends on xroad-proxy (>= 6.16.0); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-metaservices (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-opmonitoring:
 xroad-addon-opmonitoring depends on xroad-proxy (>= 6.16.0); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-opmonitoring (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-proxymonitor:
 xroad-addon-proxymonitor depends on xroad-proxy (>= 6.16.0); however:
  PackageNo apport report written because the error message indicates its a followup error from a previous failure.
     No apport report written because the error message indicates its a followup error from a previous failure.
 No apport report written because MaxReports is reached already
                                                               No apport report written because MaxReports is reached already
               No apport report written because MaxReports is reached already
                                                                             No apport report written because MaxReports is reached already
                              xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-proxymonitor (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-addon-wsdlvalidator:
 xroad-addon-wsdlvalidator depends on xroad-proxy (>= 6.16.0); however:
  Package xroad-proxy is not configured yet.

dpkg: error processing package xroad-addon-wsdlvalidator (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of xroad-securityserver:
 xroad-securityserver depends on xroad-proxy (>= 6.16.0); however:
  Package xroad-proxy is not configured yet.
 xroad-securityserver depends on xroad-addon-metaservices (>= 6.16.0); however:
  Package xroad-addon-metaservices is not configured yet.
 xroad-securityserver depends on xroad-addon-messagelog (>= 6.16.0); however:
  Package xroad-addon-messagelog is not configured yet.
 xroad-securityserver depends on xroad-addon-proxymonitor (>= 6.16.0); however:
  Package xroad-addon-proxymonitor is not configured yet.
 xroad-securityserver depends on xroad-addon-wsdlvalidator (>= 6.16.0); however:
  Package xroad-addon-wsdlvalidator is not configured yet.
 xroad-securityserver depends on xroad-addon-opmonitoring (>= 6.16.0); however:
  Package xroad-addon-opmonitoring is not configured yet.

dpkg: error processing package xroad-securityserver (--configure):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for xroad-common (6.16.0-0.20171128173309git05cf71f) ...
Errors were encountered while processing:
 xroad-proxy
 xroad-addon-messagelog
 xroad-addon-metaservices
 xroad-addon-opmonitoring
 xroad-addon-proxymonitor
 xroad-addon-wsdlvalidator
 xroad-securityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Acceptance criteria**
- ...

**Comment by mdgaffar** [comment]
[xroad_ss_github_problem.txt](https://github.com/vrk-kpa/xroad-joint-development/files/2467754/xroad_ss_github_problem.txt)

**Comment by hanhaka** [comment]
Hi,

this GitHub repository is NOT anymore used as the text on the front page shows: 
_Unmaintained repository. Development moved to: https://github.com/nordic-institute/X-Road-development_ 

Please use the above link and create the same issue into that repository. 

Regards,
Hannu

**Comment by mdgaffar** [comment]
Thank you Hannu Sir. I raised the new issue:

https://github.com/nordic-institute/X-Road-development/issues/8
