### ISSUE TITLE
As an integrator I want to be able to add filters to x-road traffic without deploying new components

### ISSUE THREAD

**Issue by andreskytt** [vrk-kpa/xroad-joint-development#24]
I want to be able to implement an application (logging, telemetry, audit, DWH etc) that 
- gets information about all x-road messages passed in both directions
- does not introduce an additional SPF or network leg 
- is asynchronous towards the x-road service

To do this, the security server should expose an API at which I can subscribe to events about messages being passed through the security server.

**Comment by petkivim** [comment]
The data that is requested is already available through environmental and operational monitoring interfaces. Changing the way how monitoring currently works in version 6 would require lot of effort and therefore, the requested changes are not implemented for version 6. Providing monitoring data as a subscription based event stream will be considered for X-Road version 7.
