### ISSUE TITLE
As X-Road user I want that Security Server would have a configurable timeout for cached TLS session with other Security Servers.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#25]
Problem:
If Producer provides a service via multiple Security Servers then if a Clients Security Server has established a TLS session with one of the Producers Security Server then all next queries will go through that cached channel. If in the future that Producers Security Server is overloaded then client would not be able to select other less loaded Providers Security Server.

Acceptance criteria:
- It must be possible to set a timeout for TLS sessions in global configuration (one minute by default)
- Clients Security Servers would be forced to search for a faster Producers Security Servers after TLS session is timed out.
- X-Road network will start to adapt to load changes, and eventually load would be distributed more evenly.

**Comment by petkivim** [comment]
Should this be a local property or a global setting that's distributed through global configuration? It seems that it's not currently possible to change the global configuration schema without breaking backwards compatibility. This means that if a new configuration item is added to the schema, all the previous security server versions quit working within the expiration period when the central server is updated and it starts to distribute the new global conf. Of course, it's possible to use extensions, but I think that TLS session timeout property would belong to global configuration core. Either way, the default timeout could be one minute.

**Comment by VitaliStupin** [comment]
I agree that timeout should belong to global configuration. But if there is a problem that we cannot extend global configuration without breaking backwards compatibility, then we should start with implementing timeout locally, After that we should probably improve global configuration management so that it would be possible to extend that without braking backwards compatibility.

**Comment by VitaliStupin** [comment]
Fixed in 6.17.0
