### ISSUE TITLE
As X-Road user I want that it would be possible to manage multiple Security Servers from one place.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#28]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
1. If independent Security Servers are offering services of the same X-Road member or its subsystem (fail-over variant), then Services ACL (Services Access Control List, or in that case services execution rights given to X-Road members and subsystems) must be identical at any point of time.
2. If multiple security servers are put behind a load balancer, then all of them must have an identical configuration (including Services ACL and keys) at any point of time.

Usage of management API (as described in #22) should be considered so simplify propagation of changes.

**Acceptance criteria**
- It is possible to easily manage multiple Security Servers offering the same services in both fail-over and load balancing variants.

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
