### ISSUE TITLE
As X-Road user I want more cost effective trust service consumption.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#30]
**Affected components**: Signer?
**Affected documentation**: UG-SS, UG-SYSPAR
**Estimated delivery**: -
**External reference**: -

**Problem**
OCSP is periodically prefetched by Security Server even if no messages are transmitted. Additionally prefetching is currently done 10 times more frequently then it is required by ocspFreshnessSeconds global configuration parameter.

If central monitoring is aggressively collecting data, then fresh OCSP would be necessary all the time, but with disabled prefetching consumption of OCSP service would still be 10 times lower.

It must also be noted that if OCSP is not prefetched then requests may be slower or even fail if it is needed to fetch OCSP during that request.

To lower the cost of trust services the following strategies may be used:
1. Disabling OCSP prefetching
2. Scheduling OCSP prefetching (e.g. prefetching only works during working hours)
3. The relation between interval of OCSP prefetching and ocspFreshnessSeconds parameter could be configurable. For example fetching would be done every ocspFreshnessSeconds/N where 
N is configurable and N can be between 2 and 10.

**Acceptance criteria**
- Trust service service consumption can be configured to be more cost effective.

**Comment by JyrgenSuvalov** [comment]
Can be closed.
