### ISSUE TITLE
As X-Road user I want that signature format used by X-Road would be better documented.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#31]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
There is a need for better documentation of signature format used by X-Road. Documentation must be supplied with examples so that it would be possible to build external validators.

**Acceptance criteria**
- New document is created and contains useful examples

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
