### ISSUE TITLE
As X-Road user I want that Security Server logs would be securely chained and timstaped

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#32]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
To provide better security all logs produced by Security Server could be chained and timestamped.

**Acceptance criteria**
- Logs are chained and timestamped without the need for external tools.

**Comment by JyrgenSuvalov** [comment]
Can be closed.
