### ISSUE TITLE
As X-Road user I want that Security Server and Central Server configurations would be automatically backuped.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#33]
**Affected components**: -
**Affected documentation**: UG-SS, UG-CS, UG-SYSPAR
**Estimated delivery**: -
**External reference**: -

**Problem**
Security Server and Central Server do not automatically backup configuration. Both servers should automatically do periodical backups.

**Acceptance criteria**
- Automatic backups are working by default.
- Backup interval can be configured (or disabled) in configuration file.
- This feature is documented in user guides.
- Automatic backup should have a distinguishable name (for example conf_automatic_backup*).
- It is possible to configure (or disable) the limit for automatic backups (last X are preserved)

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
