### ISSUE TITLE
As Security Server administrator I want to receive notifications when Consumer systems do not use unique message identifiers.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#34]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
When Consumer system does not provide unique identifiers of X-Road messages in SOAP headers, then it is complicated to search for a specific message log item. Security Server administrator needs to know if message identifiers are not unique so that it would be possible to fix that problem as soon as possible.

Check of the uniqueness of identifiers should be performed in the background so that delivery of the messages would not be influenced. For example that check can be performed during archiving of message logs from database to the file system.

Currently there in no notification system in security server, so information about duplicates should be printed into logs using WARNING log level.

This issue is closely related to #21.

**Acceptance criteria**
- Security Server administrator can see information about duplicates in logs.

**Comment by JyrgenSuvalov** [comment]
Can be closed.
