### ISSUE TITLE
As Central Server administrator I want that joining with test instances would not require manual approval.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#35]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
It must be possible to configure (for test environments) X-Road instance to automatically accept new members, security servers, and subsystems without manual insertion of these into Central Server.

**Acceptance criteria**
- Test instances can be configured to work without manual approval

**Comment by JyrgenSuvalov** [comment]
This can be closed.
