### ISSUE TITLE
As X-Road user I want that CSR format would be automatically selected.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#36]
**Affected components**: Global Configuration, Security Server UI, Central Server UI
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.ria.ee/browse/XTE-187

**Problem**
It must be possible to save in X-Road Center the preference for CSR (certificate signing request) format for every trust service provider. Generation of CSR in security server must automatically select the correct format (DER/PEM).

**Acceptance criteria**
- Generation of CSR in security server automatically selects the correct format

**Comment by JyrgenSuvalov** [comment]
Can be closed
