### ISSUE TITLE
As X-Road user I want to see subsystem full name

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#37]
**Affected components**: Central Server UI, Security Server UI, Global Configuration, meta-services
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.ria.ee/browse/XTE-149

**Problem**
Subsystem names do not provide necessary context. For administrators it is useful to additionally see the full names of subsystems. Full name should be visible not only in the web interface of Security and Central Servers, but also in the output of meta-services.

**Acceptance criteria**
- It is possible to use subsystem full name

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
