### ISSUE TITLE
As X-Road copyright owner I want that web interfaces would be checked for compatibility with NFR 4.*.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#40]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
It is not known if Web interfaces are compatible with NFR 4.*

**Acceptance criteria**
- Compatibility check is performed

**Comment by hvainsalu** [comment]
As agreed in the workgroup (2017-10-12) this task includes the following NFR items: 4.1 / 4.2 / 4.3 / 4.4

**Comment by petkivim** [comment]
Making the current code base compliant with the requirements requires effort and does not provide significant additional value. However, the requirements were added to NFR for a reason. Therefore, the requirements will be kept in NFR, but not applied to the current code base. Instead, the requirements will be applied to new components/extensions and the next version of X-Road.
