### ISSUE TITLE
BUG: NFR 5.2.1 - Components of X-Road MUST NOT use unconfigured (hard-coded) references to files or external systems.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#41]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
Source code must conform to NFR (https://github.com/vrk-kpa/xroad-joint-development/blob/master/NFR.md)

**Acceptance criteria**
- Source code conforms to NFR

**Comment by petkivim** [comment]
Making the current code base compliant with the requirements requires effort and does not provide significant additional value. However, the requirements were added to NFR for a reason. Therefore, the requirements will be kept in NFR, but not applied to the current code base. Instead, the requirements will be applied to new components/extensions and the next version of X-Road.
