### ISSUE TITLE
As X-Road developer I want Security Requirements document to be created (NFR 6.1)

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#44]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
NFR 6.1 (https://github.com/vrk-kpa/xroad-joint-development/blob/master/NFR.md) points to not-existent Security Requirements document. Developers need that document for better understanding of X-Road security requirements.

**Acceptance criteria**
- Security Requirements document is created

**Comment by hvainsalu** [comment]
Decided in workgroup on 12.20.2017. NFR requirement shall be dropped.
