### ISSUE TITLE
As a service provider I want to disable a subsystem temporarily so that I can do maintenance on all the services under the subsystem

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#46]
**Affected components**: xroad-jetty
**Affected documentation**: -
**Estimated delivery**: July 2016
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-399

**Acceptance criteria**
- It's possible to enable/disable a subsystem on Security Server admin UI
- When a subsystem is disabled, no queries must not be routed to it
- If the subsystem is not registered on other Security Servers, an error message stating that the subsystem is currently disabled must be returned to the client
- If the subsystem is registered on other Security Servers, the query must be routed to a Security Server where the subsystem is active

**Comment by hvainsalu** [comment]
Clustering must consider that other aspects.Further analysis on clustering and configuration options (cluster wide disablement or server specific). Under discussion for next time.

**Comment by petkivim** [comment]
Transferred to X-Road Service Desk as an enhancement request.
