### ISSUE TITLE
BUG: Restoring backup on other Security Server fails

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#47]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: May 2015
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-398

**Problem**

If configuration backup is restored on other security server `db.properties` file contains different password than the one generated during installation. Database password is not changed during the restore process which causes restore failure. If backup is restored on the same security server the problem does not occur, because the password is correct.

**Acceptance criteria**
- Database password is updated during restore process.

**Comment by hanhaka** [comment]
Fixed to version 6.7.x. Closing issue as the fix is already available.
