### ISSUE TITLE
As service provider I want that the Security Server verifies the authentication certificate of the sender before reading the SOAP request so that unknown senders can not cause security threats

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#51]
**Affected components**: server-proxy, client-proxy
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-253

**Problem**
Currently server proxy verifies the authentication certificate of the sender after reading the SOAP request. This makes it possible to send large messages without verification which might cause unwanted load to the server and slow down message processing.

**Acceptance criteria**
- Server proxy verifies the authentication certificate before reading the SOAP request which makes it more difficult for unidentified users to cause harm.

**Comment by hanhaka** [comment]
Fixed in version 6.10.0
