### ISSUE TITLE
As an information security specialist I want that embedded Jetty is upgraded to version 9 so that there are no known vulnerabilities

### ISSUE THREAD

**Issue by petkivim** [vrk-kpa/xroad-joint-development#53]
**Affected components**: server-proxy, client-proxy
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-203, https://jira.ria.ee/browse/XTE-252

**Problem**

Currently both client-proxy and server-proxy use embedded Jetty version 8 which is end-of-life (EOL) version and it is no longer supported. Due to this it is advised to update Jetty to version 9.

**Acceptance criteria**
- Embedded Jetty is upgraded to the latest version (9.x)

**Comment by hanhaka** [comment]
Agreed on 9th of August that work on this issue can be started (done by RIA side).

**Comment by VitaliStupin** [comment]
Released in version 6.12.0
