### ISSUE TITLE
Bug:AsX-Road User I need created signature becompliant to standards.

### ISSUE THREAD

**Issue by hvainsalu** [vrk-kpa/xroad-joint-development#55]
**Affected components**: messagelog, signature verification utility
**Affected documentation**: -
**Estimated delivery**: End of June.
**External reference**: https://jira.ria.ee/browse/XTE-248

**Problem**
Signatures (ASiC containers) that are created when exporting message log contents don't follow e-signature standards.
Shall this be a backward compatible solution or not?

Specific items:
- Timestamp must be inside SignatureTimeStamp/EncapsulatedTimeStamp element, but is in SignatureTimeStamp.
- DataObjectFormat element ObjectReference atribute does not reference to given data object  ds:Reference element as should be according to XAdES
- manifest.xml lacks 
  <manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.etsi.asic-e+zip"/>

**Acceptance criteria**
- ...
- does not need backward compatibility

**Comment by martinpaljak** [comment]
Where can one get a sample document and/or where in the code is the file creation happening?

**Comment by iluwatar** [comment]
ASiC containers can be obtained from security server's client proxy interface with correct parameters e.g.

`https://ss1.mydomain.com/asic?xRoadInstance=FI&memberClass=GOV&memberCode=1710128-9&subSystemCode=SS1&queryId=ID11234`

The code is mostly in asic-util module's ee.ria.xroad.common.asic package.

**Comment by martinpaljak** [comment]
Okay. Not directly related to the faulty xades structure, I'm in a need for a small and simple, unbloated Java minilibrary for ASiC containers (opendocument based). I'm not aware of any, but I know we already have two implementations (+ probably something inside sd-dss, which does not count for "unbloated").

https://github.com/martinpaljak/idcrypt/wiki/CDOC-2.0#libasic

For this specific xades issue I still have to get a sample.

**Comment by VitaliStupin** [comment]
Fixed in 6.16.0

**Comment by VitaliStupin** [comment]
Fixed in 6.16.0
