### ISSUE TITLE
As Security Server Admininstrator I want that signer retries to get the OCSP response in error situation so that recovering from error situation is faster

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#65]
**Affected components**: signer
**Affected documentation**: -
**Estimated delivery**: autumn 2016
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-459

**Problem**
Currently signer is implemented so that it is polling the OCSP responses using the time interval defined by the ocspFreshnessSeconds/10 parameter value. If an error situation realizes and valid OCSP response (or no OCSP response at all) is not received, it takes the very same polling time interval (=ocspFreshnessSeconds/10) until signer retries next time to get the OCSP response. Between that time the error situation is active.

By designing and implementing an algorithm that does the retry using more sophisticated logic, the time when error situation is active can be reduced. Within this story a new algorithm is designed and implemented targeting to improve the signer functionality.

**Acceptance criteria**
- If an error situation realizes when fetching the OCSP response or received the OCSP response is not valid, then the signer can retry to get the OCSP response by using the more sophisticated algorithm

**Comment by hanhaka** [comment]
Merged code changes to develop branch in VRK-KPA repository via commit:
https://github.com/vrk-kpa/xroad/pull/36

**Comment by alweiler** [comment]
This problem is still up 6.8.6.20161020095957 In which version problem will be solved

**Comment by hanhaka** [comment]
This issue will be solved in version 6.9.0. Version 6.9.0 will be released during the December (exact day is not yet known but we are targeting get it out before Christmas).

**Comment by hanhaka** [comment]
Commited to XM/develop (finnish-6.9.0 pull request). Will be available with 6.9 release.
