### ISSUE TITLE
Represented party header mechanism for both sender and receiver

### ISSUE THREAD

**Issue by PriitParmakson** [vrk-kpa/xroad-joint-development#68]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
"Third party representation extension of X-Road message protocol 1.0" provides a mechanism (X-Road message header `representedParty` ) to pass on the identity of the party being represented in a service request.

A similar mechanism would be needed for the cases where service provider is representing a party.  (This is exactly the case in the [DHX protocol](https://github.com/e-gov/DHX/blob/master/README.md)).

In the most general case, BOTH parties of the X-Road transaction can act as proxies for other (third and fourth) parties.

**Acceptance criteria**
- ...

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
