### ISSUE TITLE
As X-Road operator I want that the connection pool in ClientProxy is fixed so that open connections are re-used properly and resources are not wasted

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#70]
**Affected components**: ClientProxy 
**Affected documentation**: -
**Estimated delivery**: Autumn 2016
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-475

**Problem**
Logic that handles (PoolingHttpClientConnectionManager) client connections in Connection Pool is not working properly or at least optimized way. For example, it does not re-use previously opened connection but (always?) opens a new connection even the existing connection could be used. This is wasting resources and potentially causes non-closed connections to be stayed open for a long time.

**Acceptance criteria**
- Found issues in the usage of connection pool are clarified
- Found issues are fixed and the usage of connection pool is improved
- Changes are tested in development environment (like AWS CI environment) and measured to validate the correct functionality

For more information about the problem and solution how it was fixed, see the below document.

[Getting the connection pool to reuse existing connections between security servers.pdf](https://github.com/vrk-kpa/xroad-joint-development/files/555222/Getting.the.connection.pool.to.reuse.existing.connections.between.security.servers.pdf)

**Comment by hanhaka** [comment]
Working group meeting on 24th of August agreed that the implementation work on this issue can started.

**Comment by olli-lindgren** [comment]
The ticket currently lists no affected documentation, so I'll add that the System Parameters manual was updated with the new pool-related options that were added. In addition, the documentation was clarified in reference to the client-timeout parameter, which does not affect the request timeout (as it claimed), only the timeout when trying to connect. A new parameter that does affect the request timeout was added, however.

**Comment by hanhaka** [comment]
Attached (into original description field) the PDF document describing the problem and found solution in more detailed level.

**Comment by hanhaka** [comment]
Merged code changes to develop branch in VRK-KPA repository via commit:
https://github.com/vrk-kpa/xroad/pull/62

**Comment by hanhaka** [comment]
Commited to XM/develop (finnish-6.9.0 pull request). Will be available with 6.9 release.
