### ISSUE TITLE
As X-Road user I want that it would be possible to synchronize Services ACL between Security Servers.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#74]
**Affected components**: Security Server UI
**Affected documentation**: UG-SS
**Estimated delivery**: -
**External reference**: -

**Problem**
Subtask of #28. Full implementation of #28 would require a major change in architecture.

If multiple Security Servers (both independent and clustered behind a load balancer) are offering services of the same X-Road members subsystem, then it must be possible to synchronize Services ACL (Services Access Control List, or in that case services execution rights given to X-Road members and subsystems).

Solution:
It must be possible to configure each subsystems ACL to be:
- Independent - Default option, nothing is synchronized. Is identical to current implementation.
- Master - Can update configurations of slave servers.
- Slave - Receiving updates from master. All ACL operations are readonly.

A master server has the following options:
- Adding a new slave
- Removing a slave
- Checking the state of slave synchronization (is it identical to master)
- Synchronize a slave
- Synchronize all slaves

Synchronization is always performed manually to avoid propagation of unwanted changes.

**Acceptance criteria**
- ACL synchronization is implemented.
- Security Server user guide (UG-SS) is updated.

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
