### ISSUE TITLE
As Central Server administrator I want that exists Central monitoring data collector to fetch monitoring data from Security Servers

### ISSUE THREAD

**Issue by ToomasMolder** [vrk-kpa/xroad-joint-development#76]
**Affected components**: -
**Affected documentation**: - [PR-META], add reference to monitoring metaservice xroad-addon-proxymonitor
[ARC-MA](https://github.com/vrk-kpa/xroad-public/blob/master/src/doc/Monitoring-architecture.md) paragraph "Central monitoring data collector"
[PR-GCONF]
**Estimated delivery**: - 
**External reference**: - Zabbix v3.0 API documentation (https://www.zabbix.com/documentation/3.0/manual/api)
Elastic stack (Elasticsearch v2.4.x, Logstash v2.4.x, Kibana v4.6.x) (https://www.elastic.co/products)

**Problem**
Current contract to use rental solution, central "Jälgimisjaam" for data collection is ended as of Oct 26, 2016, extending of contract not possible.
Data collector has not implemented yet.
Central monitoring does not have possibility to monitor members Security Servers.
Data Collector Input - list of Security Servers from Global Configuration [PR-GCONF] and monitoring data from Security Servers according to [ARC-MA]
Data Collector Output - Zabbix (environmental monitoring) and Elastic stack (both environmental monitoring and operational monitoring)

**Acceptance criteria**
- Data collector is implemented

**Comment by VitaliStupin** [comment]
Done:
https://github.com/ria-ee/X-Road-scripts#health-and-environment-monitoring
https://github.com/ria-ee/X-Road-opmonitor
