### ISSUE TITLE
As Security Server administrator I want that during initialization server code would be checked for uniqueness.

### ISSUE THREAD

**Issue by VassilMarjunits** [vrk-kpa/xroad-joint-development#79]
**Affected components**: proxy
**Affected documentation**: -
**Estimated delivery**: -
**External reference**:  https://jira.ria.ee/browse/XTE-99

**Problem**
**Bug**. It is possible to initialize security server with **not unique code**. But its not possible to register server when code is not unique

**Acceptance criteria**
When initialize new security server need a check is the server code unique.
Show warning if same server code is already exist, and give explanation if there is no need to restore already registered server, then change server code to unique.

**Comment by VitaliStupin** [comment]
Released in version 6.12.0
