### ISSUE TITLE
As a Developer I want that the namespaces in pr-meta document would be fixed

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#83]
**Affected components**: documentation
**Affected documentation**: PR-META
**Estimated delivery**: -
**External reference**: -

**Problem**
Annex B (WSDL) defines targetNamespace="http://metadata.x-road.eu/", but in Annex C the example messages are using namespace xmlns:xroad="http://x-road.eu/xsd/xroad.xsd".

**Acceptance criteria**
- WSDL is using the correct namespace http://x-road.eu/xsd/xroad.xsd
- Document is converted to markdown.

**Comment by JyrgenSuvalov** [comment]
Transferred to X-Road Service Desk as an enhancement request.
Can be closed.
