### ISSUE TITLE
As a Product Owner I want that Security Server would work with more than 10 CPU cores.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#84]
**Affected components**: ?
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: https://jira.ria.ee/browse/XTE-294

**Problem**
If Security Server has more than 10 CPU cores then it will not work. The log will contain something like that:
```WARN o.e.jetty.server.AbstractConnector - insufficient threads configured for SelectChannelConnector@0.0.0.0:5577```

This is probably a jetty problem. A similar bug report can be found here:
https://issues.opennms.org/browse/NMS-6519

**Acceptance criteria**
- Security Server must be able to work with 10+ CPU cores.
- Constraint to CPU core amount (if any) must be documented.

**Comment by jhyoty** [comment]
Probable cause: ee.ria.xroad.proxy.util.CertHashBasedOcspResponder configures a thread pool of 5 threads which will be used up by jetty acceptor threads if there are enough cores. This might cause the component to stop responding since there are no threads available to serve the requests.

**Comment by VitaliStupin** [comment]
Problem should be fixed with embedded Jetty upgrade (#53) in version 6.11.1.
During this upgrade CertHashBasedOcspResponder thread pool configuration was changed from 5/5 to 10/200.

**Comment by VitaliStupin** [comment]
Released in version 6.12.0
