### ISSUE TITLE
Give me a TESTING EXAMPLE  please   what should I do?

### ISSUE THREAD

**Issue by 729234500** [vrk-kpa/xroad-joint-development#87]
We succeeded in building a central server and the security server and use it is testing.
Therefore, we need a real example test the security server and a central server.I hope it can be established in a real environment, rather than a test validation information system cannot,and we want to know what a real information system is a way.
So i hope give me a real open resources information system instead of a simple example.
Thanks

**Comment by petkivim** [comment]
If you want to test X-Road with a real production level information system you have three options:

1. Use your own information system and integrate it to you own X-Road instance
2. Use some open API available in the internet and integrate to your own X-Road instance
3. Join Finnish Palveluväylä (NB! only for Finnish organizations) or Estonian X-tee (NB! only for Estonian organizations) and make a service agreement with a service provider, and start using their service.

**Comment by 729234500** [comment]
Can you show me your test cases do you use?

**Comment by petkivim** [comment]
Unfortunately our automated test cases are not public yet. However, you can material about X-Road performance testing here:

https://github.com/vrk-kpa/xroad-load-tests

X-Road E2E monitoring tool:

https://github.com/vrk-kpa/xroad-e2e-client
