### ISSUE TITLE
xroad-signer after network outage or restart

### ISSUE THREAD

**Issue by alweiler** [vrk-kpa/xroad-joint-development#88]
**Affected components**:  xroad-signer
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
version 6.8.6.20161020095957

After network problem, or restart I must restart xroad-signer to see keys. We are using HSM thales netconnect. Is there any way to solve this problem

**Acceptance criteria**
- ...

**Comment by VitaliStupin** [comment]
Released in version 6.12.0
